In [1]:
import pandas as pd
import unicodedata
import re

# Data Loading and Observation
Loading and observing the data entries in the datasets from Olist.

In [2]:
# Load the customers dataset
customers_df = pd.read_csv(
    "../data/01_raw/olist_customers_dataset.csv",
    converters={
        'customer_zip_code_prefix': str # Convert ZIP codes to strings
    }
)
customers_df

customer_id                customer_unique_id  \
0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0   
1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3   
2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e   
3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c   
4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066   
...                                 ...                               ...   
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8   
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d   
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99   
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e   
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398   

      customer_zip_code_prefix          customer_city customer_state  
0                        14409                 franca             SP  
1                        09790  sao bernardo do campo             SP  
2                        01151              sao paulo             SP  
3                        08775        mogi das cruzes             SP  
4                        13056               campinas             SP  
...                        ...                    ...            ...  
99436                    03937              sao paulo             SP  
99437                    06764        taboao da serra             SP  
99438                    60115              fortaleza             CE  
99439                    92120                 canoas             RS  
99440                    06703                  cotia             SP  

[99441 rows x 5 columns]

In [3]:
# Load the geolocation dataset
geolocation_df = pd.read_csv(
    "../data/01_raw/olist_geolocation_dataset.csv",
    converters={
        'geolocation_zip_code_prefix': str # Convert ZIP codes to strings
    }
)
geolocation_df

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                             01037       -23.545621       -46.639292   
1                             01046       -23.546081       -46.644820   
2                             01046       -23.546129       -46.642951   
3                             01041       -23.544392       -46.639499   
4                             01035       -23.541578       -46.641607   
...                             ...              ...              ...   
1000158                       99950       -28.068639       -52.010705   
1000159                       99900       -27.877125       -52.224882   
1000160                       99950       -28.071855       -52.014716   
1000161                       99980       -28.388932       -51.846871   
1000162                       99950       -28.070104       -52.018658   

        geolocation_city geolocation_state  
0              sao paulo                SP  
1              sao paulo                SP  
2              sao paulo                SP  
3              sao paulo                SP  
4              sao paulo                SP  
...                  ...               ...  
1000158         tapejara                RS  
1000159   getulio vargas                RS  
1000160         tapejara                RS  
1000161  david canabarro                RS  
1000162         tapejara                RS  

[1000163 rows x 5 columns]

In [4]:
# Load the order items dataset
items_df = pd.read_csv("../data/01_raw/olist_order_items_dataset.csv")
items_df

order_id  order_item_id  \
0       00010242fe8c5a6d1ba2dd792cb16214              1   
1       00018f77f2f0320c557190d7a144bdd3              1   
2       000229ec398224ef6ca0657da4fc703e              1   
3       00024acbcdf0a6daa1e931b038114c75              1   
4       00042b26cf59d7ce69dfabb4e55b4fd9              1   
...                                  ...            ...   
112645  fffc94f6ce00a00581880bf54a75a037              1   
112646  fffcd46ef2263f404302a634eb57f7eb              1   
112647  fffce4705a9662cd70adb13d4a31832d              1   
112648  fffe18544ffabc95dfada21779c9644f              1   
112649  fffe41c64501cc87c801fd61db3f6244              1   

                              product_id                         seller_id  \
0       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
1       e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36   
2       c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d   
3       7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4   
4       ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87   
...                                  ...                               ...   
112645  4aa6014eceb682077f9dc4bffebc05b0  b8bc237ba3788b23da09c0f1f3a3288c   
112646  32e07fd915822b0765e448c4dd74c828  f3c38ab652836d21de61fb8314b69182   
112647  72a30483855e2eafc67aee5dc2560482  c3cfdc648177fdbbbb35635a37472c53   
112648  9c422a519119dcad7575db5af1ba540e  2b3e4a2a3ea8e01938cabda2a3e5cc79   
112649  350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1   

        shipping_limit_date   price  freight_value  
0       2017-09-19 09:45:35   58.90          13.29  
1       2017-05-03 11:05:13  239.90          19.93  
2       2018-01-18 14:48:30  199.00          17.87  
3       2018-08-15 10:10:18   12.99          12.79  
4       2017-02-13 13:57:51  199.90          18.14  
...                     ...     ...            ...  
112645  2018-05-02 04:11:01  299.99          43.41  
112646  2018-07-20 04:31:48  350.00          36.53  
112647  2017-10-30 17:14:25   99.90          16.95  
112648  2017-08-21 00:04:32   55.99           8.72  
112649  2018-06-12 17:10:13   43.00          12.79  

[112650 rows x 7 columns]

In [5]:
# Load the payments dataset
payments_df = pd.read_csv("../data/01_raw/olist_order_payments_dataset.csv")
payments_df

order_id  payment_sequential payment_type  \
0       b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card   
1       a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card   
2       25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card   
3       ba78997921bbcdc1373bb41e913ab953                   1  credit_card   
4       42fdf880ba16b47b59251dd489d4441a                   1  credit_card   
...                                  ...                 ...          ...   
103881  0406037ad97740d563a178ecc7a2075c                   1       boleto   
103882  7b905861d7c825891d6347454ea7863f                   1  credit_card   
103883  32609bbb3dd69b3c066a6860554a77bf                   1  credit_card   
103884  b8b61059626efa996a60be9bb9320e10                   1  credit_card   
103885  28bbae6599b09d39ca406b747b6632b1                   1       boleto   

        payment_installments  payment_value  
0                          8          99.33  
1                          1          24.39  
2                          1          65.71  
3                          8         107.78  
4                          2         128.45  
...                      ...            ...  
103881                     1         363.31  
103882                     2          96.80  
103883                     1          47.77  
103884                     5         369.54  
103885                     1         191.58  

[103886 rows x 5 columns]

In [6]:
# Load the reviews dataset
reviews_df = pd.read_csv("../data/01_raw/olist_order_reviews_dataset.csv")
reviews_df

review_id                          order_id  \
0      7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb   
1      80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33   
2      228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b   
3      e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b   
4      f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1   
...                                 ...                               ...   
99219  574ed12dd733e5fa530cfd4bbf39d7c9  2a8c23fee101d4d5662fa670396eb8da   
99220  f3897127253a9592a73be9bdfdf4ed7a  22ec9f0669f784db00fa86d035cf8602   
99221  b3de70c89b1510c4cd3d0649fd302472  55d4004744368f5571d1f590031933e4   
99222  1adeb9d84d72fe4e337617733eb85149  7725825d039fc1f0ceb7635e3f7d9206   
99223  efe49f1d6f951dd88b51e6ccd4cc548f  90531360ecb1eec2a1fbb265a0db0508   

       review_score review_comment_title  \
0                 4                  NaN   
1                 5                  NaN   
2                 5                  NaN   
3                 5                  NaN   
4                 5                  NaN   
...             ...                  ...   
99219             5                  NaN   
99220             5                  NaN   
99221             5                  NaN   
99222             4                  NaN   
99223             1                  NaN   

                                  review_comment_message review_creation_date  \
0                                                    NaN  2018-01-18 00:00:00   
1                                                    NaN  2018-03-10 00:00:00   
2                                                    NaN  2018-02-17 00:00:00   
3                  Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00   
4      Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00   
...                                                  ...                  ...   
99219                                                NaN  2018-07-07 00:00:00   
99220                                                NaN  2017-12-09 00:00:00   
99221  Excelente mochila, entrega super rápida. Super...  2018-03-22 00:00:00   
99222                                                NaN  2018-07-01 00:00:00   
99223  meu produto chegou e ja tenho que devolver, po...  2017-07-03 00:00:00   

      review_answer_timestamp  
0         2018-01-18 21:46:59  
1         2018-03-11 03:05:13  
2         2018-02-18 14:36:24  
3         2017-04-21 22:02:06  
4         2018-03-02 10:26:53  
...                       ...  
99219     2018-07-14 17:18:30  
99220     2017-12-11 20:06:42  
99221     2018-03-23 09:10:43  
99222     2018-07-02 12:59:13  
99223     2017-07-03 21:01:49  

[99224 rows x 7 columns]

In [7]:
# Load the orders dataset
orders_df = pd.read_csv("../data/01_raw/olist_orders_dataset.csv")
orders_df

order_id                       customer_id  \
0      e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
1      53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef   
2      47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089   
3      949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82   
4      ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c   
...                                 ...                               ...   
99436  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00   
99437  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7   
99438  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c   
99439  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1   
99440  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24   

      order_status order_purchase_timestamp    order_approved_at  \
0        delivered      2017-10-02 10:56:33  2017-10-02 11:07:15   
1        delivered      2018-07-24 20:41:37  2018-07-26 03:24:27   
2        delivered      2018-08-08 08:38:49  2018-08-08 08:55:23   
3        delivered      2017-11-18 19:28:06  2017-11-18 19:45:59   
4        delivered      2018-02-13 21:18:39  2018-02-13 22:20:29   
...            ...                      ...                  ...   
99436    delivered      2017-03-09 09:54:05  2017-03-09 09:54:05   
99437    delivered      2018-02-06 12:58:58  2018-02-06 13:10:37   
99438    delivered      2017-08-27 14:46:43  2017-08-27 15:04:16   
99439    delivered      2018-01-08 21:28:27  2018-01-08 21:36:21   
99440    delivered      2018-03-08 20:57:30  2018-03-09 11:20:28   

      order_delivered_carrier_date order_delivered_customer_date  \
0              2017-10-04 19:55:00           2017-10-10 21:25:13   
1              2018-07-26 14:31:00           2018-08-07 15:27:45   
2              2018-08-08 13:50:00           2018-08-17 18:06:29   
3              2017-11-22 13:39:59           2017-12-02 00:28:42   
4              2018-02-14 19:46:34           2018-02-16 18:17:02   
...                            ...                           ...   
99436          2017-03-10 11:18:03           2017-03-17 15:08:01   
99437          2018-02-07 23:22:42           2018-02-28 17:37:56   
99438          2017-08-28 20:52:26           2017-09-21 11:24:17   
99439          2018-01-12 15:35:03           2018-01-25 23:32:54   
99440          2018-03-09 22:11:59           2018-03-16 13:08:30   

      order_estimated_delivery_date  
0               2017-10-18 00:00:00  
1               2018-08-13 00:00:00  
2               2018-09-04 00:00:00  
3               2017-12-15 00:00:00  
4               2018-02-26 00:00:00  
...                             ...  
99436           2017-03-28 00:00:00  
99437           2018-03-02 00:00:00  
99438           2017-09-27 00:00:00  
99439           2018-02-15 00:00:00  
99440           2018-04-03 00:00:00  

[99441 rows x 8 columns]

In [8]:
# Load the products dataset
products_df = pd.read_csv("../data/01_raw/olist_products_dataset.csv")
products_df

product_id              product_category_name  \
0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria   
1      3aa071139cb16b67ca9e5dea641aaa2f                              artes   
2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer   
3      cef67bcfe19066a932b7673e239eb23d                              bebes   
4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas   
...                                 ...                                ...   
32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao   
32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao   
32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho   
32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios   
32950  106392145fca363410d287a815be6de4                    cama_mesa_banho   

       product_name_lenght  product_description_lenght  product_photos_qty  \
0                     40.0                       287.0                 1.0   
1                     44.0                       276.0                 1.0   
2                     46.0                       250.0                 1.0   
3                     27.0                       261.0                 1.0   
4                     37.0                       402.0                 4.0   
...                    ...                         ...                 ...   
32946                 45.0                        67.0                 2.0   
32947                 41.0                       971.0                 1.0   
32948                 50.0                       799.0                 1.0   
32949                 60.0                       156.0                 2.0   
32950                 58.0                       309.0                 1.0   

       product_weight_g  product_length_cm  product_height_cm  \
0                 225.0               16.0               10.0   
1                1000.0               30.0               18.0   
2                 154.0               18.0                9.0   
3                 371.0               26.0                4.0   
4                 625.0               20.0               17.0   
...                 ...                ...                ...   
32946           12300.0               40.0               40.0   
32947            1700.0               16.0               19.0   
32948            1400.0               27.0                7.0   
32949             700.0               31.0               13.0   
32950            2083.0               12.0                2.0   

       product_width_cm  
0                  14.0  
1                  20.0  
2                  15.0  
3                  26.0  
4                  13.0  
...                 ...  
32946              40.0  
32947              16.0  
32948              27.0  
32949              20.0  
32950               7.0  

[32951 rows x 9 columns]

In [9]:
# Load the sellers dataset
sellers_df = pd.read_csv(
    "../data/01_raw/olist_sellers_dataset.csv",
    converters={
        'seller_zip_code_prefix': str # Convert ZIP codes to strings
    }
)
sellers_df

seller_id seller_zip_code_prefix  \
0     3442f8959a84dea7ee197c632cb2df15                  13023   
1     d1b65fc7debc3361ea86b5f14c68d2e2                  13844   
2     ce3ad9de960102d0677a81f5d0bb7b2d                  20031   
3     c0f3eea2e14555b6faeea3dd58c1b1c3                  04195   
4     51a04a8a6bdcb23deccc82b0b80742cf                  12914   
...                                ...                    ...   
3090  98dddbc4601dd4443ca174359b237166                  87111   
3091  f8201cab383e484733266d1906e2fdfa                  88137   
3092  74871d19219c7d518d0090283e03c137                  04650   
3093  e603cf3fec55f8697c9059638d6c8eb5                  96080   
3094  9e25199f6ef7e7c347120ff175652c3b                  12051   

            seller_city seller_state  
0              campinas           SP  
1            mogi guacu           SP  
2        rio de janeiro           RJ  
3             sao paulo           SP  
4     braganca paulista           SP  
...                 ...          ...  
3090            sarandi           PR  
3091            palhoca           SC  
3092          sao paulo           SP  
3093            pelotas           RS  
3094            taubate           SP  

[3095 rows x 4 columns]

In [10]:
# Load the product category name translation dataset
translations_df = pd.read_csv("../data/01_raw/product_category_name_translation.csv")
translations_df

product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

# Data Quality Check
Identifies any data quality issues.

## Overview
High level overview of the structure of the datasets.

In [11]:
# Obtain a high level overview of the data in the customers dataset
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  object
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: object(5)
memory usage: 3.8+ MB


In [12]:
# Obtain a high level overview of the data in the geolocation dataset
geolocation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype  
---  ------                       --------------    -----  
 0   geolocation_zip_code_prefix  1000163 non-null  object 
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object 
 4   geolocation_state            1000163 non-null  object 
dtypes: float64(2), object(3)
memory usage: 38.2+ MB


In [13]:
# Obtain a high level overview of the data in the items dataset
items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   order_id             112650 non-null  object 
 1   order_item_id        112650 non-null  int64  
 2   product_id           112650 non-null  object 
 3   seller_id            112650 non-null  object 
 4   shipping_limit_date  112650 non-null  object 
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB


In [14]:
# Obtain a high level overview of the data in the payments dataset
payments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   order_id              103886 non-null  object 
 1   payment_sequential    103886 non-null  int64  
 2   payment_type          103886 non-null  object 
 3   payment_installments  103886 non-null  int64  
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB


In [15]:
# Obtain a high level overview of the data in the reviews dataset
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64 
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB


In [16]:
# Obtain a high level overview of the data in the orders dataset
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype 
---  ------                         --------------  ----- 
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB


In [17]:
# Obtain a high level overview of the data in the products dataset
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   product_id                  32951 non-null  object 
 1   product_category_name       32341 non-null  object 
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB


In [18]:
# Obtain a high level overview of the data in the sellers dataset
sellers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   object
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: object(4)
memory usage: 96.8+ KB


In [19]:
# Obtain a high level overview of the data in the translations dataset
translations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype 
---  ------                         --------------  ----- 
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB


Notes:
- *No One-to-One Relationship*: All the datasets have different number of rows, suggesting that there is not a one-to-one relationship between any of the datasets.
- *Missing Values - Reviews*: The reviews dataset contains a significant number of missing comment titles and messages. review_comment_title has only 11568 non-null values and review_comment_message only has 40977 non-null values out of the 99 224 rows.
- *Missing Values - Orders*: The orders dataset contains a slight amount of missing values in the approval date, delivered carrier date, and delivered customer date.
- *Missing Values - Products*: The products dataset also contains a small amount of missing values in all columns except product_id.

Datasets With Missing Entries:
- reviews
- orders
- products

## Distributions
Obtain a high-level overview of the distributions of data in the datasets.

In [20]:
# Observe the data distributions in the customers dataset
customers_df.describe()

customer_id                customer_unique_id  \
count                              99441                             99441   
unique                             99441                             96096   
top     274fa6071e5e17fe303b9748641082c8  8d50f5eadf50201ccdcedfb9e2ac8455   
freq                                   1                                17   

       customer_zip_code_prefix customer_city customer_state  
count                     99441         99441          99441  
unique                    14994          4119             27  
top                       22790     sao paulo             SP  
freq                        142         15540          41746

In [188]:
# Observe the distribution of different cities
customers_df['customer_city'].value_counts()

customer_city
sao paulo                15540
rio de janeiro            6882
belo horizonte            2773
brasilia                  2131
curitiba                  1521
                         ...  
marques de souza             1
general maynard              1
cerrito                      1
mocajuba                     1
governador mangabeira        1
Name: count, Length: 4119, dtype: int64

Notes:
- All customer_id entries are unique as count and unique are equal (99441).
- There are 96096 unique customers in the dataset which is shown as there are 96096 unique customer_unique_id.
- Not all customer_zip_code_prefix are unique, up to 142 customers are living in the same zip code area.
- Sao paulo citizens are the highest proportion of Olist's customers, with 15 540 customers from Sao Paulo.
- SP state citizens are the highest proportion of Olist's customers, with 41 746 customers from SP.
- The formatting of the customer city may need to be investigated further as the cities in the geolocation and sellers datasets have encoding errors and inconsistent spellings. Investigated in Customer Check.

In [21]:
# Set float display format to prevent scientific notation
pd.options.display.float_format = '{:.5f}'.format

# Observe the data distributions in the geolocations dataset
geolocation_df.describe(include=['float64', 'object']).round(2)

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
count                      1000163    1000163.00000    1000163.00000   
unique                       19015              NaN              NaN   
top                          24220              NaN              NaN   
freq                          1146              NaN              NaN   
mean                           NaN        -21.18000        -46.39000   
std                            NaN          5.72000          4.27000   
min                            NaN        -36.61000       -101.47000   
25%                            NaN        -23.60000        -48.57000   
50%                            NaN        -22.92000        -46.64000   
75%                            NaN        -19.98000        -43.77000   
max                            NaN         45.07000        121.11000   

       geolocation_city geolocation_state  
count           1000163           1000163  
unique             8011                27  
top           sao paulo                SP  
freq             135800            404268  
mean                NaN               NaN  
std                 NaN               NaN  
min                 NaN               NaN  
25%                 NaN               NaN  
50%                 NaN               NaN  
75%                 NaN               NaN  
max                 NaN               NaN

In [22]:
# Reset the display format back to the default
pd.reset_option('display.float_format')

In [23]:
# Observe the distribution of different cities
geolocation_df['geolocation_city'].value_counts()

geolocation_city
sao paulo         135800
rio de janeiro     62151
belo horizonte     27805
são paulo          24918
curitiba           16593
                   ...  
sao bras               1
são brás               1
ibitiranga             1
quixabá                1
maceia³                1
Name: count, Length: 8011, dtype: int64

In [24]:
# Check a sample zip code
geolocation_df[geolocation_df['geolocation_zip_code_prefix']=='45936']

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
694783                       45936       -12.883913       -38.478122   
694790                       45936       -17.999945       -39.868270   
694792                       45936       -12.903227       -38.308831   
694832                       45936       -12.921871       -38.491053   
694905                       45936       -18.000329       -39.867793   
694910                       45936       -12.807618       -38.395391   
694939                       45936       -18.010597       -39.864476   
694996                       45936       -18.006772       -39.863218   
695000                       45936       -14.670199       -40.489571   
695014                       45936       -12.921859       -38.441688   
695026                       45936       -18.010727       -39.853151   
695033                       45936       -12.972809       -38.492293   
695077                       45936       -18.006085       -39.869503   
695078                       45936       -18.012923       -39.853185   
695082                       45936       -18.000563       -39.872925   
695098                       45936       -17.998612       -39.863092   
695113                       45936       -12.903227       -38.308831   
695179                       45936       -18.006458       -39.863305   
695220                       45936       -18.005224       -39.863065   
695272                       45936       -18.004717       -39.862340   
695285                       45936       -12.903227       -38.308831   
695293                       45936       -18.000833       -39.866641   
695375                       45936       -34.622400       -58.901888   
695377                       45936        38.323939        -6.775035   
695380                       45936       -18.011086       -39.854250   
695383                       45936       -12.881923       -38.480661   
695384                       45936       -12.971700       -38.513649   
695437                       45936       -15.812589       -40.216908   
695459                       45936       -12.168931       -45.005067   
695462                       45936       -18.007946       -39.863437   
695517                       45936       -12.953699       -38.399041   
695536                       45936       -18.007846       -39.863429   
695553                       45936       -11.301073       -41.844488   
695560                       45936       -18.011263       -39.853380   
695596                       45936       -18.005224       -39.863065   

         geolocation_city geolocation_state  
694783           itabatan                BA  
694790            itabata                BA  
694792            itabata                BA  
694832           itabatan                BA  
694905            itabata                BA  
694910            itabata                BA  
694939            itabata                BA  
694996            itabata                BA  
695000            itabata                BA  
695014            itabata                BA  
695026             mucuri                BA  
695033           itabatan                BA  
695077  itabatan (mucuri)                BA  
695078  itabatan (mucuri)                BA  
695082           itabatan                BA  
695098            itabata                BA  
695113            itabata                BA  
695179           itabatan                BA  
695220             mucuri                BA  
695272           itabatan                BA  
695285            itabata                BA  
695293           itabatan                BA  
695375            itabata                BA  
695377           itabatan                BA  
695380           itabatan                BA  
695383           itabatan                BA  
695384            itabata                BA  
695437           itabatan                BA  
695459            itabata                BA  
695462            itabata         

Notes:
- **Brazil's True Lat and Lng**: The range of Brazils latitude is between -33.742. and 5.272. The range of Brazils longitude is between -73.992 and -34.792. [(Shaalaa, 2025)](https://www.shaalaa.com/question-bank-solutions/describe-the-latitudinal-and-longitudinal-extent-of-india-and-brazil_75800)
- **Erroneous Lat and Lng**: The max geolocation latitude is 45.07000. Furthermore, the geolocation longitude range is between -101.47000	and 121.11000, suggesting that there are entries which are outside Brazil's longitude and latitude. This suggests that the geolocation entries contain entries which are not located in Brazil. Investigated in Geolocation Check.
- **Inconsistent Use of Diacritics**: Some city values in the dataset are spelt without the diacritics and some are spelt with it. For example, there are values of 'sao bras' and 'sao brás'. Must be standardised in data cleaning.
- **Potential Encoding Errors**: 'Maceió' is spelled as 'maceia³'. The superscript 3 and change from 'o' to 'a' is likely caused by an encoding error. Must be corrected in data cleaning. Investigated further in Geolocation Check
- **Inconsistent Spelling**: Some zip codes have different spellings for the city such as itabata, itabatan, mucuri which refer to the same city. These need to be normalized by aggregating it and using the mode of the city for that zip code.

In [25]:
# Observe the data distributions in the items dataset
items_df.describe(include=['float64', 'int64', 'object'])

order_id  order_item_id  \
count                             112650  112650.000000   
unique                             98666            NaN   
top     8272b63d03f5f79c56e9e4120aec44ef            NaN   
freq                                  21            NaN   
mean                                 NaN       1.197834   
std                                  NaN       0.705124   
min                                  NaN       1.000000   
25%                                  NaN       1.000000   
50%                                  NaN       1.000000   
75%                                  NaN       1.000000   
max                                  NaN      21.000000   

                              product_id                         seller_id  \
count                             112650                            112650   
unique                             32951                              3095   
top     aca2eb7d00ea1a7b8ebd4e68314663af  6560211a19b47992c3666cc44a7e94c0   
freq                                 527                              2033   
mean                                 NaN                               NaN   
std                                  NaN                               NaN   
min                                  NaN                               NaN   
25%                                  NaN                               NaN   
50%                                  NaN                               NaN   
75%                                  NaN                               NaN   
max                                  NaN                               NaN   

        shipping_limit_date          price  freight_value  
count                112650  112650.000000  112650.000000  
unique                93318            NaN            NaN  
top     2018-03-01 02:50:48            NaN            NaN  
freq                     21            NaN            NaN  
mean                    NaN     120.653739      19.990320  
std                     NaN     183.633928      15.806405  
min                     NaN       0.850000       0.000000  
25%                     NaN      39.900000      13.080000  
50%                     NaN      74.990000      16.260000  
75%                     NaN     134.900000      21.150000  
max                     NaN    6735.000000     409.680000

Notes:
- **Products with Free Delivery**: The minimum freight_value is 0 suggesting that delivery is free for some products.
- **Large Quantity Orders**: One product was purchased in a large quantity, purchasing 21 of the same product in the same order. This is shown as the max value in order_item_id is 21, suggesting that there was a specific product that was purchased 21 times in the same order. This may be an important product that needs to be investigated in the EDA.

In [26]:
# Observe the data distributions in the payments dataset
payments_df.describe(include=['float64', 'int64', 'object'])

order_id  payment_sequential payment_type  \
count                             103886       103886.000000       103886   
unique                             99440                 NaN            5   
top     fa65dad1b0e818e3ccc5cb0e39231352                 NaN  credit_card   
freq                                  29                 NaN        76795   
mean                                 NaN            1.092679          NaN   
std                                  NaN            0.706584          NaN   
min                                  NaN            1.000000          NaN   
25%                                  NaN            1.000000          NaN   
50%                                  NaN            1.000000          NaN   
75%                                  NaN            1.000000          NaN   
max                                  NaN           29.000000          NaN   

        payment_installments  payment_value  
count          103886.000000  103886.000000  
unique                   NaN            NaN  
top                      NaN            NaN  
freq                     NaN            NaN  
mean                2.853349     154.100380  
std                 2.687051     217.494064  
min                 0.000000       0.000000  
25%                 1.000000      56.790000  
50%                 1.000000     100.000000  
75%                 4.000000     171.837500  
max                24.000000   13664.080000

Notes:
- **High Payment Sequential**: There are customers who want to pay with up to 29 payment sequences which is an outlier as it seems too tedious to pay an order using multiple sequences of payment.
- **High Payment Installments**: There are orders which can be paid by up to 24 payment installments. This is shown as the max payment_installments is 24. This outlier suggests a high cost order.
- **Free Orders**: Some orders are free. The min payment_value is 0 suggesting that some orders are completely free. This will be investigated further in Payment Check.

In [27]:
# Observe the data distributions in the reviews dataset
reviews_df.describe(include=['float64', 'int64', 'object'])

review_id                          order_id  \
count                              99224                             99224   
unique                             98410                             98673   
top     08528f70f579f0c830189efc523d2182  df56136b8031ecd28e200bb18e6ddb2e   
freq                                   3                                 3   
mean                                 NaN                               NaN   
std                                  NaN                               NaN   
min                                  NaN                               NaN   
25%                                  NaN                               NaN   
50%                                  NaN                               NaN   
75%                                  NaN                               NaN   
max                                  NaN                               NaN   

        review_score review_comment_title review_comment_message  \
count   99224.000000                11568                  40977   
unique           NaN                 4527                  36159   
top              NaN            Recomendo              Muito bom   
freq             NaN                  423                    230   
mean        4.086421                  NaN                    NaN   
std         1.347579                  NaN                    NaN   
min         1.000000                  NaN                    NaN   
25%         4.000000                  NaN                    NaN   
50%         5.000000                  NaN                    NaN   
75%         5.000000                  NaN                    NaN   
max         5.000000                  NaN                    NaN   

       review_creation_date review_answer_timestamp  
count                 99224                   99224  
unique                  636                   98248  
top     2017-12-19 00:00:00     2017-06-15 23:21:05  
freq                    463                       4  
mean                    NaN                     NaN  
std                     NaN                     NaN  
min                     NaN                     NaN  
25%                     NaN                     NaN  
50%                     NaN                     NaN  
75%                     NaN                     NaN  
max                     NaN                     NaN

Notes:
- Generally, the olist's orders are completed with good reviews. The median review score is 5, and the 25% percentile of the review score is 4 which is still decent.
- Majority of the reviews do not have a title or a message. The count of review_comment_title and review_comment_message, 11568 and 40977 respectively, are significantly lower than the number of reviews in the dataset (99224). 

In [28]:
# Observe the data distributions in the orders dataset
orders_df.describe(include=['float64', 'int64', 'object'])

order_id                       customer_id  \
count                              99441                             99441   
unique                             99441                             99441   
top     66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24   
freq                                   1                                 1   

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281   
unique            8                    98875                90733   
top       delivered      2018-08-02 12:05:26  2018-02-27 04:31:10   
freq          96478                        3                    9   

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476   
unique                        81018                         95664   
top             2018-05-09 15:48:00           2018-05-08 19:36:48   
freq                             47                             3   

       order_estimated_delivery_date  
count                          99441  
unique                           459  
top              2017-12-20 00:00:00  
freq                             522

Notes:
- This dataset identifies the state of the order in the supply chain.
- The missing values in the order_approved_at, order_delivered_carrier_date,order_delivered_customer_date fields is likely due to the status of the order, having not passed certain parts of the supply chain yet. Investigated further in Null Check - Orders.

In [29]:
# Observe the data distributions in the products dataset
products_df.describe(include=['float64', 'int64', 'object'])

product_id product_category_name  \
count                              32951                 32341   
unique                             32951                    73   
top     106392145fca363410d287a815be6de4       cama_mesa_banho   
freq                                   1                  3029   
mean                                 NaN                   NaN   
std                                  NaN                   NaN   
min                                  NaN                   NaN   
25%                                  NaN                   NaN   
50%                                  NaN                   NaN   
75%                                  NaN                   NaN   
max                                  NaN                   NaN   

        product_name_lenght  product_description_lenght  product_photos_qty  \
count          32341.000000                32341.000000        32341.000000   
unique                  NaN                         NaN                 NaN   
top                     NaN                         NaN                 NaN   
freq                    NaN                         NaN                 NaN   
mean              48.476949                  771.495285            2.188986   
std               10.245741                  635.115225            1.736766   
min                5.000000                    4.000000            1.000000   
25%               42.000000                  339.000000            1.000000   
50%               51.000000                  595.000000            1.000000   
75%               57.000000                  972.000000            3.000000   
max               76.000000                 3992.000000           20.000000   

        product_weight_g  product_length_cm  product_height_cm  \
count       32949.000000       32949.000000       32949.000000   
unique               NaN                NaN                NaN   
top                  NaN                NaN                NaN   
freq                 NaN                NaN                NaN   
mean         2276.472488          30.815078          16.937661   
std          4282.038731          16.914458          13.637554   
min             0.000000           7.000000           2.000000   
25%           300.000000          18.000000           8.000000   
50%           700.000000          25.000000          13.000000   
75%          1900.000000          38.000000          21.000000   
max         40425.000000         105.000000         105.000000   

        product_width_cm  
count       32949.000000  
unique               NaN  
top                  NaN  
freq                 NaN  
mean           23.196728  
std            12.079047  
min             6.000000  
25%            15.000000  
50%            20.000000  
75%            30.000000  
max           118.000000

Notes:
- There is a product that weights 0g. This outlier is potentially a data entry error as products should have a mass. Investigated in Product Weight Check.
- There is an anomalously long product_description_lenght entry with 3992 characters. This may be using many different tags to push the product in search results. This may be investigated in the EDA.
- There are products which have anomalously high product_photos_qty (20). More pictures may improve customer satisfaction with the product ordered as they may be more aware of what the product will look like. This may be investigated in the EDA.

In [30]:
# Observe the data distributions in the sellers dataset
sellers_df.describe(include=['float64', 'int64', 'object'])

seller_id seller_zip_code_prefix seller_city  \
count                               3095                   3095        3095   
unique                              3095                   2246         611   
top     9e25199f6ef7e7c347120ff175652c3b                  14940   sao paulo   
freq                                   1                     49         694   

       seller_state  
count          3095  
unique           23  
top              SP  
freq           1849

In [31]:
# Observe the distribution of different seller_city
sellers_df['seller_city'].value_counts()

seller_city
sao paulo            694
curitiba             127
rio de janeiro        96
belo horizonte        68
ribeirao preto        52
                    ... 
massaranduba           1
cornelio procopio      1
alvorada               1
ipaussu                1
congonhal              1
Name: count, Length: 611, dtype: int64

Notes:
- Contains information of where the sellers reside.
- Seller cities will need to be investigated further to identify if there are encoding errors or inconsistent use of diacritics.

In [32]:
# Observe the data distributions in the sellers dataset
translations_df.describe(include=['float64', 'int64', 'object'])

product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

Notes:
- Can be useful to understand the categories of the products in English.

## Null Check
Investigates the missing values identified in the Overview section.

In [33]:
# Calculates the percentage of null entries in each column i.e. number of null entries / number of entries in the column
def calculate_null_proportion_per_column(df):
    num_null_entries_per_column = df.isnull().sum()
    total_rows = df.shape[0]
    null_proportion = num_null_entries_per_column/total_rows *100
    print("% of null entries per column:")
    return null_proportion.round(2)

# Calculates the number and percentage of rows with at least one null entry
def count_rows_with_nulls(df):
    # Count rows with at least one null
    num_rows_with_nulls = df.isnull().any(axis=1).sum()
    total_rows = df.shape[0]
    percent_rows_with_null = (num_rows_with_nulls / total_rows) * 100  # Calculate percentage

    # Display results
    print(f"No. rows with at least one null value: {num_rows_with_nulls}")
    print(f"% of rows with at least one null value: {percent_rows_with_null:.2f}%")

The following datasets have missing values and will be the only ones investigated in this section
- Reviews
- Orders
- Products

The other datasets do not have null values in them and will not need to be investigated for null values.

### Reviews
Investigates the missing values in the reviews dataset

In [34]:
# Investigate the proportion of null entries in each data field of the reviews dataset
calculate_null_proportion_per_column(reviews_df)

% of null entries per column:


review_id                   0.00
order_id                    0.00
review_score                0.00
review_comment_title       88.34
review_comment_message     58.70
review_creation_date        0.00
review_answer_timestamp     0.00
dtype: float64

In [35]:
# Identify the number of rows with at least 1 null value in the reviews dataset
count_rows_with_nulls(reviews_df)

No. rows with at least one null value: 89385
% of rows with at least one null value: 90.08%


In [36]:
# Identify the rows of data with missing comment titles
missing_comment_titles_df = reviews_df[reviews_df['review_comment_title'].isnull()]
missing_comment_titles_df.head()

review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb   
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33   
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b   
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b   
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1   

   review_score review_comment_title  \
0             4                  NaN   
1             5                  NaN   
2             5                  NaN   
3             5                  NaN   
4             5                  NaN   

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00   
1                                                NaN  2018-03-10 00:00:00   
2                                                NaN  2018-02-17 00:00:00   
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00   
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00   

  review_answer_timestamp  
0     2018-01-18 21:46:59  
1     2018-03-11 03:05:13  
2     2018-02-18 14:36:24  
3     2017-04-21 22:02:06  
4     2018-03-02 10:26:53

In [37]:
# Identify the rows of data with missing comment messages
missing_comment_message_df = reviews_df[reviews_df['review_comment_message'].isnull()]
missing_comment_message_df.head()

review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb   
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33   
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b   
5  15197aa66ff4d0650b5434f1b46cda19  b18dcdf73be66366873cd26c5724d1dc   
6  07f9bee5d1b850860defd761afa7ff16  e48aa0d2dcec3a2e87348811bcfdf22b   

   review_score review_comment_title review_comment_message  \
0             4                  NaN                    NaN   
1             5                  NaN                    NaN   
2             5                  NaN                    NaN   
5             1                  NaN                    NaN   
6             5                  NaN                    NaN   

  review_creation_date review_answer_timestamp  
0  2018-01-18 00:00:00     2018-01-18 21:46:59  
1  2018-03-10 00:00:00     2018-03-11 03:05:13  
2  2018-02-17 00:00:00     2018-02-18 14:36:24  
5  2018-04-13 00:00:00     2018-04-16 00:39:37  
6  2017-07-16 00:00:00     2017-07-18 19:30:34

In [38]:
# Identify the rows of data with missing comment messages but with a comment title
missing_message_existing_title_df = reviews_df[
    reviews_df['review_comment_message'].isnull() & reviews_df['review_comment_title'].notnull()
]
missing_message_existing_title_df.head()

review_id                          order_id  \
53   1edd1a85161468a77e5fcb165be9b294  d8e17cc85323061493b16b68a130bcff   
104  352609f0f2d34ce5d3b8de817ee948d5  96b947c986b42f213c9e6b8ccccedb89   
220  a89a2b0c2014bc49a0f87f1eedb7b269  22b1eef278d4416c1e867a55d1c39fea   
225  cdc5c81bd9377ccbf9cb95f05648c31b  18956b40b774d6384c8539cd61784bd7   
495  b50001aa0bbd7557c4ad80eee167a2a1  daece90b61801c766fe21e0922574566   

     review_score       review_comment_title review_comment_message  \
53              5                      Ótimo                    NaN   
104             3      Não recebi o produto.                    NaN   
220             5  Entrega antes do previsto                    NaN   
225             5                  Recomendo                    NaN   
495             5                     Ótimo                     NaN   

    review_creation_date review_answer_timestamp  
53   2018-06-02 00:00:00     2018-06-02 23:15:37  
104  2018-08-25 00:00:00     2018-08-25 20:53:41  
220  2018-05-26 00:00:00     2018-05-28 22:46:27  
225  2018-06-22 00:00:00     2018-06-24 23:07:08  
495  2018-05-05 00:00:00     2018-05-07 17:12:36

Notes:
- There is a substantially large proportion of missing entries for review_comment_title (88.34%). This is not anomalous as the reviewer likely wanted to leave a brief review without any need for a title. The system for making the review likely did not require a title.
- There is also a significant proportion of missing entries for review_comment_message (55.70%). This is not anomalous as the reviewer likely did not want to elaborate on details of the product in the review. The system for making the review likely did not require the user to write a review message too.
- These rows should not be dropped as they are not data entry errors - the reviewer just did not want to enter a title or message.
- These features are likely not important for EDA and modeling for determining if customers will return. Furthermore, they have a substantial number of null entries (>50%), which thus cannot be imputed. Hence, they will be dropped in feature selection. 

### Orders
Investigates the missing values in the orders dataset

In [39]:
# Investigate the proportion of null entries in each data field of the orders dataset
calculate_null_proportion_per_column(orders_df)

% of null entries per column:


order_id                         0.00
customer_id                      0.00
order_status                     0.00
order_purchase_timestamp         0.00
order_approved_at                0.16
order_delivered_carrier_date     1.79
order_delivered_customer_date    2.98
order_estimated_delivery_date    0.00
dtype: float64

In [40]:
# Identify the number of rows with at least 1 null value in the orders dataset
count_rows_with_nulls(orders_df)

No. rows with at least one null value: 2980
% of rows with at least one null value: 3.00%


In [41]:
# Identify rows with missing order approved dates
missing_approved_df = orders_df[orders_df['order_approved_at'].isnull()]
missing_approved_df.head()

order_id                       customer_id  \
1130  00b1cb0320190ca0daa2c88b35206009  3532ba38a3fd242259a514ac2b6ae6b6   
1801  ed3efbd3a87bea76c2812c66a0b32219  191984a8ba4cbb2145acb4fe35b69664   
1868  df8282afe61008dc26c6c31011474d02  aa797b187b5466bc6925aaaa4bb3bed1   
2029  8d4c637f1accf7a88a4555f02741e606  b1dd715db389a2077f43174e7a675d07   
2161  7a9d4c7f9b068337875b95465330f2fc  7f71ae48074c0cfec9195f88fcbfac55   

     order_status order_purchase_timestamp order_approved_at  \
1130     canceled      2018-08-28 15:26:39               NaN   
1801     canceled      2018-09-20 13:54:16               NaN   
1868     canceled      2017-03-04 12:14:30               NaN   
2029     canceled      2018-08-29 16:27:49               NaN   
2161     canceled      2017-05-01 16:12:39               NaN   

     order_delivered_carrier_date order_delivered_customer_date  \
1130                          NaN                           NaN   
1801                          NaN                           NaN   
1868                          NaN                           NaN   
2029                          NaN                           NaN   
2161                          NaN                           NaN   

     order_estimated_delivery_date  
1130           2018-09-12 00:00:00  
1801           2018-10-17 00:00:00  
1868           2017-04-10 00:00:00  
2029           2018-09-13 00:00:00  
2161           2017-05-30 00:00:00

In [42]:
# Identify the types of order statuses associated with missing order_approved_at data
missing_approved_df['order_status'].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [43]:
# Observe the rows whose order statuses are delivered or created which are also missing order_approved_at data
incorrect_approved_df = missing_approved_df[missing_approved_df["order_status"]=='delivered']
incorrect_approved_df

order_id                       customer_id  \
5323   e04abd8149ef81b95221e88f6ed9ab6a  2127dc6603ac33544953ef05ec155771   
16567  8a9adc69528e1001fc68dd0aaebbb54a  4c1ccc74e00993733742a3c786dc3c1f   
19031  7013bcfc1c97fe719a7b5e05e61c12db  2941af76d38100e0f8740a374f1a5dc3   
22663  5cf925b116421afa85ee25e99b4c34fb  29c35fc91fc13fb5073c8f30505d860d   
23156  12a95a3c06dbaec84bcfb0e2da5d228a  1e101e0daffaddce8159d25a8e53f2b2   
26800  c1d4211b3dae76144deccd6c74144a88  684cb238dc5b5d6366244e0e0776b450   
38290  d69e5d356402adc8cf17e08b5033acfb  68d081753ad4fe22fc4d410a9eb1ca01   
39334  d77031d6a3c8a52f019764e68f211c69  0bf35cac6cc7327065da879e2d90fae8   
48401  7002a78c79c519ac54022d4f8a65e6e8  d5de688c321096d15508faae67a27051   
61743  2eecb0d85f281280f79fa00f9cec1a95  a3d3c38e58b9d2dfb9207cab690b6310   
63052  51eb2eebd5d76a24625b31c33dd41449  07a2a7e0f63fd8cb757ed77d4245623c   
67697  88083e8f64d95b932164187484d90212  f67cd1a215aae2a1074638bbd35a223a   
72407  3c0b8706b065f9919d0505d3b3343881  d85919cb3c0529589c6fa617f5f43281   
84999  2babbb4b15e6d2dfe95e2de765c97bce  74bebaf46603f9340e3b50c6b086f992   

      order_status order_purchase_timestamp order_approved_at  \
5323     delivered      2017-02-18 14:40:00               NaN   
16567    delivered      2017-02-18 12:45:31               NaN   
19031    delivered      2017-02-18 13:29:47               NaN   
22663    delivered      2017-02-18 16:48:35               NaN   
23156    delivered      2017-02-17 13:05:55               NaN   
26800    delivered      2017-01-19 12:48:08               NaN   
38290    delivered      2017-02-19 01:28:47               NaN   
39334    delivered      2017-02-18 11:04:19               NaN   
48401    delivered      2017-01-19 22:26:59               NaN   
61743    delivered      2017-02-17 17:21:55               NaN   
63052    delivered      2017-02-18 15:52:27               NaN   
67697    delivered      2017-02-18 22:49:19               NaN   
72407    delivered      2017-02-17 15:53:27               NaN   
84999    delivered      2017-02-18 17:15:03               NaN   

      order_delivered_carrier_date order_delivered_customer_date  \
5323           2017-02-23 12:04:47           2017-03-01 13:25:33   
16567          2017-02-23 09:01:52           2017-03-02 10:05:06   
19031          2017-02-22 16:25:25           2017-03-01 08:07:38   
22663          2017-02-22 11:23:10           2017-03-09 07:28:47   
23156          2017-02-22 11:23:11           2017-03-02 11:09:19   
26800          2017-01-25 14:56:50           2017-01-30 18:16:01   
38290          2017-02-23 03:11:48           2017-03-02 03:41:58   
39334          2017-02-23 07:23:36           2017-03-02 16:15:23   
48401          2017-01-27 11:08:05           2017-02-06 14:22:19   
61743          2017-02-22 11:42:51           2017-03-03 12:16:03   
63052          2017-02-23 03:09:14           2017-03-07 13:57:47   
67697          2017-02-22 11:31:06           2017-03-02 12:06:06   
72407          2017-02-22 11:31:30           2017-03-03 11:47:47   
84999          2017-02-22 11:23:11           2017-03-03 18:43:43   

      order_estimated_delivery_date  
5323            2017-03-17 00:00:00  
16567           2017-03-21 00:00:00  
19031           2017-03-17 00:00:00  
22663           2017-03-31 00:00:00  
23156           2017-03-20 00:00:00  
26800           2017-03-01 00:00:00  
38290           2017-03-27 00:00:00  
39334           2017-03-22 00:00:00  
48401           2017-03-16 00:00:00  
61743           2017-03-20 00:00:00  
63052           2017-03-29 00:00:00  
67697           2017-03-21 00:00:00  
72407           2017-03-23 00:00:00  
84999           2017-03-31 00:00:00

In [44]:
# Display the number of rows with the erroneous missing order_approved_at data
erroneous_entries_count = incorrect_approved_df.shape[0]
print("Number of erroneous missing entries:", erroneous_entries_count)

Number of erroneous missing entries: 14


These entries are erroneous as they are missing the order approved date. These entries suggest that the orders were already approved and that the products were already delivered. These entries should have an approved date as the order should have already passed the approval stage by the time it was delivered.

In [45]:
# Identify rows with missing order_delivered_carrier_date entries
missing_carrier_df = orders_df[orders_df['order_delivered_carrier_date'].isnull()]
missing_carrier_df

order_id                       customer_id  \
6      136cce7faa42fdb2cefd53fdc79a6098  ed0271e0b7da060a393796590e7b737a   
103    0760a852e4e9d89eb77bf631eaaf1c84  d2a79636084590b7465af8ab374a8cf5   
128    15bed8e2fec7fdbadb186b57c46c92f2  f3f0e613e0bdb9c7cee75504f0f90679   
266    8e24261a7e58791d10cb1bf9da94df5c  64a254d30eed42cd0e6c36dddb88adf0   
324    d3c8851a6651eeff2f73b0e011ac45d0  957f8e082185574de25992dc659ebbc0   
...                                 ...                               ...   
99283  3a3cddda5a7c27851bd96c3313412840  0b0d6095c5555fe083844281f6b093bb   
99313  e9e64a17afa9653aacf2616d94c005b8  b4cd0522e632e481f8eaf766a2646e86   
99347  a89abace0dcc01eeb267a9660b5ac126  2f0524a7b1b3845a1a57fcf3910c4333   
99348  a69ba794cc7deb415c3e15a0a3877e69  726f0894b5becdf952ea537d5266e543   
99415  5fabc81b6322c8443648e1b21a6fef21  32c9df889d41b0ee8309a5efb6855dcb   

      order_status order_purchase_timestamp    order_approved_at  \
6         invoiced      2017-04-11 12:22:08  2017-04-13 13:25:17   
103       invoiced      2018-08-03 17:44:42  2018-08-07 06:15:14   
128     processing      2017-09-03 14:22:03  2017-09-03 14:30:09   
266    unavailable      2017-11-16 15:09:28  2017-11-16 15:26:57   
324     processing      2016-10-05 22:44:13  2016-10-06 15:51:05   
...            ...                      ...                  ...   
99283     canceled      2018-08-31 16:13:44                  NaN   
99313   processing      2018-01-05 23:07:24  2018-01-09 07:18:05   
99347     canceled      2018-09-06 18:45:47                  NaN   
99348  unavailable      2017-08-23 16:28:04  2017-08-28 15:44:47   
99415  unavailable      2017-10-10 10:50:03  2017-10-14 18:35:57   

      order_delivered_carrier_date order_delivered_customer_date  \
6                              NaN                           NaN   
103                            NaN                           NaN   
128                            NaN                           NaN   
266                            NaN                           NaN   
324                            NaN                           NaN   
...                            ...                           ...   
99283                          NaN                           NaN   
99313                          NaN                           NaN   
99347                          NaN                           NaN   
99348                          NaN                           NaN   
99415                          NaN                           NaN   

      order_estimated_delivery_date  
6               2017-05-09 00:00:00  
103             2018-08-21 00:00:00  
128             2017-10-03 00:00:00  
266             2017-12-05 00:00:00  
324             2016-12-09 00:00:00  
...                             ...  
99283           2018-10-01 00:00:00  
99313           2018-02-06 00:00:00  
99347           2018-09-27 00:00:00  
99348           2017-09-15 00:00:00  
99415           2017-10-23 00:00:00  

[1783 rows x 8 columns]

In [46]:
# Identify the types of order statuses associated with missing order_delivered_carrier_date data
missing_carrier_df['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [47]:
# Observe the entries with the 'delivered' status
erroneous_carrier_df = missing_carrier_df[missing_carrier_df['order_status']=='delivered']
erroneous_carrier_df

order_id                       customer_id  \
73222  2aa91108853cecb43c84a5dc5b277475  afeb16c7f46396c0ed54acb45ccaaa40   
92643  2d858f451373b04fb5c984a1cc2defaf  e08caf668d499a6d643dafd7c5cc498a   

      order_status order_purchase_timestamp    order_approved_at  \
73222    delivered      2017-09-29 08:52:58  2017-09-29 09:07:16   
92643    delivered      2017-05-25 23:22:43  2017-05-25 23:30:16   

      order_delivered_carrier_date order_delivered_customer_date  \
73222                          NaN           2017-11-20 19:44:47   
92643                          NaN                           NaN   

      order_estimated_delivery_date  
73222           2017-11-14 00:00:00  
92643           2017-06-23 00:00:00

These 2 data entries are erroneously missing as they should have the order_delivered_carrier_date values. The products were already delivered to the customers by the carrier, which means the carrier must have received the products beforehand. Therefore, the order_delivered_carrier_date should have been recorded for these entries. However, since these 2 data entries are missing the order_delivered_carrier_date values, they are erroneous. This feature is likely not important for EDA and modeling for determining the customers return and likely removed in feature selection. This also ensures that these row entries will not be dropped entirely, preserving the other data features for EDA and modelling purposes.

In [48]:
# Identify rows with missing order_delivered_customer_date entries
missing_delivered_customer_df = orders_df[orders_df['order_delivered_customer_date'].isnull()]
missing_delivered_customer_df

order_id                       customer_id  \
6      136cce7faa42fdb2cefd53fdc79a6098  ed0271e0b7da060a393796590e7b737a   
44     ee64d42b8cf066f35eac1cf57de1aa85  caded193e8e47b8362864762a83db3c5   
103    0760a852e4e9d89eb77bf631eaaf1c84  d2a79636084590b7465af8ab374a8cf5   
128    15bed8e2fec7fdbadb186b57c46c92f2  f3f0e613e0bdb9c7cee75504f0f90679   
154    6942b8da583c2f9957e990d028607019  52006a9383bf149a4fb24226b173106f   
...                                 ...                               ...   
99283  3a3cddda5a7c27851bd96c3313412840  0b0d6095c5555fe083844281f6b093bb   
99313  e9e64a17afa9653aacf2616d94c005b8  b4cd0522e632e481f8eaf766a2646e86   
99347  a89abace0dcc01eeb267a9660b5ac126  2f0524a7b1b3845a1a57fcf3910c4333   
99348  a69ba794cc7deb415c3e15a0a3877e69  726f0894b5becdf952ea537d5266e543   
99415  5fabc81b6322c8443648e1b21a6fef21  32c9df889d41b0ee8309a5efb6855dcb   

      order_status order_purchase_timestamp    order_approved_at  \
6         invoiced      2017-04-11 12:22:08  2017-04-13 13:25:17   
44         shipped      2018-06-04 16:44:48  2018-06-05 04:31:18   
103       invoiced      2018-08-03 17:44:42  2018-08-07 06:15:14   
128     processing      2017-09-03 14:22:03  2017-09-03 14:30:09   
154        shipped      2018-01-10 11:33:07  2018-01-11 02:32:30   
...            ...                      ...                  ...   
99283     canceled      2018-08-31 16:13:44                  NaN   
99313   processing      2018-01-05 23:07:24  2018-01-09 07:18:05   
99347     canceled      2018-09-06 18:45:47                  NaN   
99348  unavailable      2017-08-23 16:28:04  2017-08-28 15:44:47   
99415  unavailable      2017-10-10 10:50:03  2017-10-14 18:35:57   

      order_delivered_carrier_date order_delivered_customer_date  \
6                              NaN                           NaN   
44             2018-06-05 14:32:00                           NaN   
103                            NaN                           NaN   
128                            NaN                           NaN   
154            2018-01-11 19:39:23                           NaN   
...                            ...                           ...   
99283                          NaN                           NaN   
99313                          NaN                           NaN   
99347                          NaN                           NaN   
99348                          NaN                           NaN   
99415                          NaN                           NaN   

      order_estimated_delivery_date  
6               2017-05-09 00:00:00  
44              2018-06-28 00:00:00  
103             2018-08-21 00:00:00  
128             2017-10-03 00:00:00  
154             2018-02-07 00:00:00  
...                             ...  
99283           2018-10-01 00:00:00  
99313           2018-02-06 00:00:00  
99347           2018-09-27 00:00:00  
99348           2017-09-15 00:00:00  
99415           2017-10-23 00:00:00  

[2965 rows x 8 columns]

In [49]:
# Identify the types of order statuses associated with missing order_delivered_customer_date data
missing_delivered_customer_df['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [50]:
# Observe the entries with the 'delivered' status
erroneous_delivered_customer_df = missing_delivered_customer_df[missing_delivered_customer_df['order_status']=='delivered']
erroneous_delivered_customer_df

order_id                       customer_id  \
3002   2d1e2d5bf4dc7227b3bfebb81328c15f  ec05a6d8558c6455f0cbbd8a420ad34f   
20618  f5dd62b788049ad9fc0526e3ad11a097  5e89028e024b381dc84a13a3570decb4   
43834  2ebdfc4f15f23b91474edf87475f108e  29f0540231702fda0cfdee0a310f11aa   
79263  e69f75a717d64fc5ecdfae42b2e8e086  cfda40ca8dd0a5d486a9635b611b398a   
82868  0d3268bad9b086af767785e3f0fc0133  4f1d63d35fb7c8999853b2699f5c7649   
92643  2d858f451373b04fb5c984a1cc2defaf  e08caf668d499a6d643dafd7c5cc498a   
97647  ab7c89dc1bf4a1ead9d6ec1ec8968a84  dd1b84a7286eb4524d52af4256c0ba24   
98038  20edc82cf5400ce95e1afacc25798b31  28c37425f1127d887d7337f284080a0f   

      order_status order_purchase_timestamp    order_approved_at  \
3002     delivered      2017-11-28 17:44:07  2017-11-28 17:56:40   
20618    delivered      2018-06-20 06:58:43  2018-06-20 07:19:05   
43834    delivered      2018-07-01 17:05:11  2018-07-01 17:15:12   
79263    delivered      2018-07-01 22:05:55  2018-07-01 22:15:14   
82868    delivered      2018-07-01 21:14:02  2018-07-01 21:29:54   
92643    delivered      2017-05-25 23:22:43  2017-05-25 23:30:16   
97647    delivered      2018-06-08 12:09:39  2018-06-08 12:36:39   
98038    delivered      2018-06-27 16:09:12  2018-06-27 16:29:30   

      order_delivered_carrier_date order_delivered_customer_date  \
3002           2017-11-30 18:12:23                           NaN   
20618          2018-06-25 08:05:00                           NaN   
43834          2018-07-03 13:57:00                           NaN   
79263          2018-07-03 13:57:00                           NaN   
82868          2018-07-03 09:28:00                           NaN   
92643                          NaN                           NaN   
97647          2018-06-12 14:10:00                           NaN   
98038          2018-07-03 19:26:00                           NaN   

      order_estimated_delivery_date  
3002            2017-12-18 00:00:00  
20618           2018-07-16 00:00:00  
43834           2018-07-30 00:00:00  
79263           2018-07-30 00:00:00  
82868           2018-07-24 00:00:00  
92643           2017-06-23 00:00:00  
97647           2018-06-26 00:00:00  
98038           2018-07-19 00:00:00

These 8 data entries are erroneous as they should have the order_delivered_carrier_date values as they were already delivered to the customer as shown by the order status being 'delivered'. Despite this, the 'order_delivered_customer_date' value is missing, suggesting that these data entries are erroneous.

order_approved_at:
- There is a very small proportion of rows with missing order_approved_at dates (0.16%). 
- 155 of these rows are valid as the orders were either created or canceled and therefore not approved and hence will not have an approved date. 
- However, there are 14 entries which are actually erroneous. 
- These orders were already delivered, suggesting that they must have been approved already, yet they are missing their order_approved_at dates. Hence, these orders are erroneous. 

order_delivered_carrier_date:
- There are small proportions of null entries in the order_delivered_carrier_date (1.79%). 
- 1781 of these entries are valid and do not need to be dropped as the orders were not delivered to the carrier and therefore do not have a order_delivered_carrier_date entry.
- 2 of these entries are erroneous. These 2 orders have already been delivered to the customer by the carrier. This suggests that there should be an order_delivered_carrier_date for these 2 data entries. However, they do not exist and hence these missing values are erroneous.

order_delivered_customer_date:
- There are small proportions of null entries in the order_delivered_carrier_date (2.98%).
- 2957 of the entries are valid as the order was not delivered to the customer and therefore it would make sense that there would be a missing order_delivered_customer__date value.
- The other 8 of these entries are erroneous. The orders were already delivered, as shown in their order_status field, however, the date in which the customer received it was not entered into the dataset in the order_delivered_customer_date field. Hence, these 8 entries are erroneous data entries.

General Notes:
- While erroneous, the entries/rows identified with missing order_delivered_carrier_date and order_approved_at should not be dropped as the other fields may be used in EDA or modeling. Instead, these 2 fields should be dropped as the date of the approval should not affect the EDA or the modelling process as they are not critical to determining the potential for customers to return. The customer will only really care about the date in which the product is delivered to them after purchasing it.
- The order_delivered_customer_date field cannot be dropped, however, as it may give insights into whether the timeliness of the delivery impacts whether customers return. Instead, feature engineering should be conducted to create a new column that represents the difference in date in which the product was received. 

### Products
Investigates the missing values in the products dataset

In [51]:
# Investigate the proportion of null entries in each data field of the products dataset
calculate_null_proportion_per_column(products_df)

% of null entries per column:


product_id                    0.00
product_category_name         1.85
product_name_lenght           1.85
product_description_lenght    1.85
product_photos_qty            1.85
product_weight_g              0.01
product_length_cm             0.01
product_height_cm             0.01
product_width_cm              0.01
dtype: float64

In [52]:
# Identify the number of rows with at least 1 null value in the products dataset
count_rows_with_nulls(products_df)

No. rows with at least one null value: 611
% of rows with at least one null value: 1.85%


In [53]:
# Identify the rows with at least 1 null value
products_df[products_df.isnull().any(axis=1)]

product_id product_category_name  \
105    a41e356c76fab66334f36de622ecbd3a                   NaN   
128    d8dee61c2034d6d075997acef1870e9b                   NaN   
145    56139431d72cd51f19eb9f7dae4d1617                   NaN   
154    46b48281eb6d663ced748f324108c733                   NaN   
197    5fb61f482620cb672f5e586bb132eae9                   NaN   
...                                 ...                   ...   
32515  b0a0c5dd78e644373b199380612c350a                   NaN   
32589  10dbe0fbaa2c505123c17fdc34a63c56                   NaN   
32616  bd2ada37b58ae94cc838b9c0569fecd8                   NaN   
32772  fa51e914046aab32764c41356b9d4ea4                   NaN   
32852  c4ceee876c82b8328e9c293fa0e1989b                   NaN   

       product_name_lenght  product_description_lenght  product_photos_qty  \
105                    NaN                         NaN                 NaN   
128                    NaN                         NaN                 NaN   
145                    NaN                         NaN                 NaN   
154                    NaN                         NaN                 NaN   
197                    NaN                         NaN                 NaN   
...                    ...                         ...                 ...   
32515                  NaN                         NaN                 NaN   
32589                  NaN                         NaN                 NaN   
32616                  NaN                         NaN                 NaN   
32772                  NaN                         NaN                 NaN   
32852                  NaN                         NaN                 NaN   

       product_weight_g  product_length_cm  product_height_cm  \
105               650.0               17.0               14.0   
128               300.0               16.0                7.0   
145               200.0               20.0               20.0   
154             18500.0               41.0               30.0   
197               300.0               35.0                7.0   
...                 ...                ...                ...   
32515            1800.0               30.0               20.0   
32589             800.0               30.0               10.0   
32616             200.0               21.0                8.0   
32772            1300.0               45.0               16.0   
32852             700.0               28.0                3.0   

       product_width_cm  
105                12.0  
128                20.0  
145                20.0  
154                41.0  
197                12.0  
...                 ...  
32515              70.0  
32589              23.0  
32616              16.0  
32772              45.0  
32852              43.0  

[611 rows x 9 columns]

In [54]:
# Identify the rows with missing product_category_name
products_df[products_df['product_category_name'].isnull()]

product_id product_category_name  \
105    a41e356c76fab66334f36de622ecbd3a                   NaN   
128    d8dee61c2034d6d075997acef1870e9b                   NaN   
145    56139431d72cd51f19eb9f7dae4d1617                   NaN   
154    46b48281eb6d663ced748f324108c733                   NaN   
197    5fb61f482620cb672f5e586bb132eae9                   NaN   
...                                 ...                   ...   
32515  b0a0c5dd78e644373b199380612c350a                   NaN   
32589  10dbe0fbaa2c505123c17fdc34a63c56                   NaN   
32616  bd2ada37b58ae94cc838b9c0569fecd8                   NaN   
32772  fa51e914046aab32764c41356b9d4ea4                   NaN   
32852  c4ceee876c82b8328e9c293fa0e1989b                   NaN   

       product_name_lenght  product_description_lenght  product_photos_qty  \
105                    NaN                         NaN                 NaN   
128                    NaN                         NaN                 NaN   
145                    NaN                         NaN                 NaN   
154                    NaN                         NaN                 NaN   
197                    NaN                         NaN                 NaN   
...                    ...                         ...                 ...   
32515                  NaN                         NaN                 NaN   
32589                  NaN                         NaN                 NaN   
32616                  NaN                         NaN                 NaN   
32772                  NaN                         NaN                 NaN   
32852                  NaN                         NaN                 NaN   

       product_weight_g  product_length_cm  product_height_cm  \
105               650.0               17.0               14.0   
128               300.0               16.0                7.0   
145               200.0               20.0               20.0   
154             18500.0               41.0               30.0   
197               300.0               35.0                7.0   
...                 ...                ...                ...   
32515            1800.0               30.0               20.0   
32589             800.0               30.0               10.0   
32616             200.0               21.0                8.0   
32772            1300.0               45.0               16.0   
32852             700.0               28.0                3.0   

       product_width_cm  
105                12.0  
128                20.0  
145                20.0  
154                41.0  
197                12.0  
...                 ...  
32515              70.0  
32589              23.0  
32616              16.0  
32772              45.0  
32852              43.0  

[610 rows x 9 columns]

Notes:
- From briefly observing the products dataset above, the null values in product_category_name, product_name_lenght, product_description_lenght, and product_photos_qty occur together. This can also be seen as the proportions of null values in these fields are equal (1.85%).
- These entries are likely data entry errors as usually products will come with a name for customers to search, identify and order. Furthermore, since these missing entries occur together, it suggests a data entry issue in the system, likely due to it not being able to retrieve the information of these products.
- These entries/rows will need to be imputed as product_description_lenght may be used in the EDA and modelling as the use of longer text and tags may affect online search results.
- These entries can be imputed as they are only 1.85% of the dataset, which is small and negligible.
- The information of the other columns can likely support the imputation as similar product dimensions may suggest similar products and thus similar product names, descriptions, photos and category.

In [55]:
# Identify the rows with missing product_weight_g
products_df[products_df['product_weight_g'].isnull()]

product_id product_category_name  \
8578   09ff539a621711667c43eba6a3bd8466                 bebes   
18851  5eb564652db742ff8f28759cd8d2652a                   NaN   

       product_name_lenght  product_description_lenght  product_photos_qty  \
8578                  60.0                       865.0                 3.0   
18851                  NaN                         NaN                 NaN   

       product_weight_g  product_length_cm  product_height_cm  \
8578                NaN                NaN                NaN   
18851               NaN                NaN                NaN   

       product_width_cm  
8578                NaN  
18851               NaN

Notes:
- The missing values in product_weight_g, product_length_cm, product_height_cm, and product_width_cm occur together as well.
- There are 2 entries which have missing values in these 4 fields.
- These are also likely data entry errors due to the system not being able to obtain information of the product as these missing values occur together, suggesting the system was unable to obtain the dimension information of the product.
- The 2nd row in the dataset shown directly above must be dropped as it does not contain any information of the product and theres not enough contextual information in the other columns to impute it accurately.
- The first row's product_weight_g, product_length_cm, product_height_cm, and product_width_cm can be imputed as well using the data in the other fields. It can be imputed as it is only 1 row of the entire dataset.

### Null Check Summary
**Reviews**:
- Drop the fields review_comment_title and review_comment_message as they have a substantial proportion (>50%) of missing values that cannot be imputed effectively.

**Orders**
- Drop the order_approved_at, order_delivered_carrier_date, order_delivered_carrier_date fields as they contain missing values and they may not be important for EDA and modeling.

**Products**:
- Drop rows of products without any information in them.
- Impute missing entries in the products dataset using iterative imputers.

## Duplicate Check

In [56]:
# Calculates the number and proportion of rows which are duplicate entries
def duplicate_entries_search(df):
    # Identify total number of rows in the dataset
    total_rows = df.shape[0]

    # Count duplicate rows
    num_duplicate_rows = df.duplicated().sum()
    percent_duplicate_rows = (num_duplicate_rows / total_rows) * 100

    # Display results
    print(f"Total duplicate rows: {num_duplicate_rows}")
    print(f"% of duplicate rows: {percent_duplicate_rows:.2f}%")


# Calculates the number and proportion of rows which have duplicate values in a specified data field
def duplicate_values_search(df, field):
    # Identify total number of rows in the dataset
    total_rows = df.shape[0]

    # Count duplicate values in the data field
    num_duplicate_values = df[field].duplicated().sum()
    proportion_duplicate_values = (num_duplicate_values / total_rows) * 100

    # Display results
    print(f"\n{field}:")
    print(f"Total duplicate entries: {num_duplicate_values}")
    print(f"% of duplicate entries: {proportion_duplicate_values:.2f}%")


In [57]:
# Identify the duplicate entries in the customers dataset
duplicate_entries_search(customers_df)
duplicate_values_search(customers_df, 'customer_id')

Total duplicate rows: 0
% of duplicate rows: 0.00%

customer_id:
Total duplicate entries: 0
% of duplicate entries: 0.00%


Customers dataset:
- There are no duplicate data in the customers dataset.

In [58]:
geolocation_df.sort_values(by='geolocation_zip_code_prefix')

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
1246                          01001       -23.549292       -46.633559   
429                           01001       -23.550498       -46.634338   
1182                          01001       -23.549779       -46.633957   
1435                          01001       -23.549292       -46.633559   
326                           01001       -23.551427       -46.634074   
...                             ...              ...              ...   
1000026                       99980       -28.388679       -51.848863   
999950                        99980       -28.388400       -51.845225   
1000002                       99980       -28.388342       -51.845194   
999864                        99990       -28.329472       -51.769109   
999758                        99990       -28.329718       -51.769615   

        geolocation_city geolocation_state  
1246           sao paulo                SP  
429            sao paulo                SP  
1182           sao paulo                SP  
1435           sao paulo                SP  
326            sao paulo                SP  
...                  ...               ...  
1000026  david canabarro                RS  
999950   david canabarro                RS  
1000002  david canabarro                RS  
999864         muliterno                RS  
999758         muliterno                RS  

[1000163 rows x 5 columns]

In [59]:
# Identify the duplicate entries in the geolocation dataset
duplicate_entries_search(geolocation_df)
duplicate_values_search(geolocation_df, 'geolocation_zip_code_prefix')

Total duplicate rows: 261831
% of duplicate rows: 26.18%

geolocation_zip_code_prefix:
Total duplicate entries: 981148
% of duplicate entries: 98.10%


In [60]:
# Observe the duplicate rows in the geolocations dataset
geolocation_df[geolocation_df.duplicated(keep=False)]

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                             01037       -23.545621       -46.639292   
1                             01046       -23.546081       -46.644820   
2                             01046       -23.546129       -46.642951   
6                             01047       -23.546273       -46.641225   
7                             01013       -23.546923       -46.634264   
...                             ...              ...              ...   
1000153                       99970       -28.343273       -51.873734   
1000154                       99950       -28.070493       -52.011342   
1000159                       99900       -27.877125       -52.224882   
1000160                       99950       -28.071855       -52.014716   
1000162                       99950       -28.070104       -52.018658   

        geolocation_city geolocation_state  
0              sao paulo                SP  
1              sao paulo                SP  
2              sao paulo                SP  
6              sao paulo                SP  
7              sao paulo                SP  
...                  ...               ...  
1000153          ciriaco                RS  
1000154         tapejara                RS  
1000159   getulio vargas                RS  
1000160         tapejara                RS  
1000162         tapejara                RS  

[390005 rows x 5 columns]

In [61]:
# Observe the duplicate values in the geolocations dataset of the geolocation_zip_code_prefix field
geolocation_df[geolocation_df['geolocation_zip_code_prefix'].duplicated(keep=False)].sort_values(by='geolocation_zip_code_prefix')

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
864                          01001       -23.549825       -46.633970   
583                          01001       -23.551337       -46.634027   
596                          01001       -23.550498       -46.634338   
1246                         01001       -23.549292       -46.633559   
1062                         01001       -23.550498       -46.634338   
...                            ...              ...              ...   
999950                       99980       -28.388400       -51.845225   
999897                       99980       -28.386408       -51.844876   
999924                       99980       -28.387693       -51.843881   
999864                       99990       -28.329472       -51.769109   
999758                       99990       -28.329718       -51.769615   

       geolocation_city geolocation_state  
864           sao paulo                SP  
583           sao paulo                SP  
596           sao paulo                SP  
1246          sao paulo                SP  
1062          sao paulo                SP  
...                 ...               ...  
999950  david canabarro                RS  
999897  david canabarro                RS  
999924  david canabarro                RS  
999864        muliterno                RS  
999758        muliterno                RS  

[999120 rows x 5 columns]

These duplicate values provide other latitude and longitude values that are within the zip codes in Brazil. However, since the 'geolocation_zip_code_prefix' will be used as the foreign key for merging with other datasets, keeping these duplicate values will cause the downstream merging to explode with more rows and multiple latitude and longitude values for each zip code which will not be useful for the EDA. Hence, entries with duplicate zip codes should be aggregated in their longitude and latitude to prevent it from occuring during the EDA and preventing the data from skewing the downstream modelling.

Geolocations dataset:
- 26.18% of the geolocations entries are duplicate. They will need to be dropped as they are unnecessary.
- 98.10% of the geolocation_zip_code_prefix values are duplicate. They need to be aggregated for EDA and modeling.

In [62]:
# Identify the duplicate entries in the items dataset
duplicate_entries_search(items_df)

Total duplicate rows: 0
% of duplicate rows: 0.00%


Items Dataset:
- No duplicate data entries.

In [63]:
# Identify the duplicate entries in the payments dataset
duplicate_entries_search(payments_df)

Total duplicate rows: 0
% of duplicate rows: 0.00%


Payments Dataset:
- No duplicate data entries.

In [64]:
# Identify the duplicate entries in the reviews dataset
duplicate_entries_search(reviews_df)
duplicate_values_search(reviews_df, 'review_id')
duplicate_values_search(reviews_df, 'order_id')

Total duplicate rows: 0
% of duplicate rows: 0.00%

review_id:
Total duplicate entries: 814
% of duplicate entries: 0.82%

order_id:
Total duplicate entries: 551
% of duplicate entries: 0.56%


In [65]:
# Identify the entries with duplicate review_id, including the first of each unique review_id
duplicate_review_id_df = reviews_df[reviews_df['review_id'].duplicated(keep=False)].sort_values(by='review_id')
duplicate_review_id_df

review_id                          order_id  \
46678  00130cbe1f9d422698c812ed8ded1919  dfcdfc43867d1c1381bfaf62d6b9c195   
29841  00130cbe1f9d422698c812ed8ded1919  04a28263e085d399c97ae49e0b477efa   
90677  0115633a9c298b6a98bcbe4eee75345f  78a4201f58af3463bdab842eea4bc801   
63193  0115633a9c298b6a98bcbe4eee75345f  0c9850b2c179c1ef60d2855e2751d1fa   
92876  0174caf0ee5964646040cd94e15ac95e  f93a732712407c02dce5dd5088d0f47b   
...                                 ...                               ...   
31120  fe5c833752953fed3209646f1f63b53c  4863e15fa53273cc7219c58f5ffda4fb   
7870   ff2fc9e68f8aabfbe18d710b83aabd30  2da58e0a7dcfa4ce1e00fad9d03ca3b5   
82521  ff2fc9e68f8aabfbe18d710b83aabd30  1078d496cc6ab9a8e6f2be77abf5091b   
73951  ffb8cff872a625632ac983eb1f88843c  c44883fc2529b4aa03ca90e7e09d95b6   
1985   ffb8cff872a625632ac983eb1f88843c  c88b1d1b157a9999ce368f218a407141   

       review_score review_comment_title  \
46678             1                  NaN   
29841             1                  NaN   
90677             5                  NaN   
63193             5                  NaN   
92876             1                  NaN   
...             ...                  ...   
31120             1                  NaN   
7870              2                  NaN   
82521             2                  NaN   
73951             3                  NaN   
1985              3                  NaN   

                                  review_comment_message review_creation_date  \
46678  O cartucho "original HP" 60XL não é reconhecid...  2018-03-07 00:00:00   
29841  O cartucho "original HP" 60XL não é reconhecid...  2018-03-07 00:00:00   
90677                                                NaN  2017-09-21 00:00:00   
63193                                                NaN  2017-09-21 00:00:00   
92876  Produto entregue dentro de embalagem do fornec...  2018-03-07 00:00:00   
...                                                  ...                  ...   
31120  Comprei dois produtos e ambos, mesmo enviados ...  2018-02-28 00:00:00   
7870                                                 NaN  2018-03-17 00:00:00   
82521                                                NaN  2018-03-17 00:00:00   
73951                                                NaN  2017-07-22 00:00:00   
1985                                                 NaN  2017-07-22 00:00:00   

      review_answer_timestamp  
46678     2018-03-20 18:08:23  
29841     2018-03-20 18:08:23  
90677     2017-09-26 03:27:47  
63193     2017-09-26 03:27:47  
92876     2018-03-08 03:00:53  
...                       ...  
31120     2018-02-28 13:57:52  
7870      2018-03-19 11:44:15  
82521     2018-03-19 11:44:15  
73951     2017-07-26 13:41:07  
1985      2017-07-26 13:41:07  

[1603 rows x 7 columns]

The entries with duplicate review_id values are potentially erroneous. The review in index 46678 is similar to the review in index 29841, only their order ids are different, as shown in the first 2 rows of the table above. These duplicate entries will need to be investigated further. 
Potential Scenarios:
- May be data entry error and they will need to be dropped as they may impact the distributions identified in the EDA or skew the model after training.
- Olist's review system allows reviews to be applied to multiple orders.

In [66]:
# Identify the order ids associated with the reviews
duplicate_reviews_order_ids = duplicate_review_id_df['order_id'].iloc[:2]

# Investigate the review message found in the first 2 rows
duplicate_review_id_df['review_comment_message'].iloc[0]

'O cartucho "original HP" 60XL não é reconhecido pela impressora, consequentemente não funcionou. Além de ter chegado com atraso de mais de 15 dias do previsto. Preciso que seja trocado. '

Translation: 
'The "original HP" 60XL cartridge is not recognized by the printer, therefore it did not work. In addition to arriving more than 15 days later than expected. I need it changed. '

In [67]:
# Merge the table above with the items dataset to obtain the order ids corresponding product
duplicate_review_id_products_df = duplicate_review_id_df.merge(items_df, on="order_id", how="left")

# Merge the table above with the items dataset to obtain the product ids corresponding product details
duplicate_review_id_products_df = duplicate_review_id_products_df.merge(products_df, on="product_id", how="left")

# Drop the null values in the comment message data field to compare the duplicate reviews to identify what the review was talking about
duplicate_review_id_products_df = duplicate_review_id_products_df.dropna(subset=['review_comment_message'])

# Observe the reviews and their corresponding products
duplicate_review_id_products_df


review_id                          order_id  \
0     00130cbe1f9d422698c812ed8ded1919  dfcdfc43867d1c1381bfaf62d6b9c195   
1     00130cbe1f9d422698c812ed8ded1919  04a28263e085d399c97ae49e0b477efa   
5     0174caf0ee5964646040cd94e15ac95e  f93a732712407c02dce5dd5088d0f47b   
6     0174caf0ee5964646040cd94e15ac95e  74db91e33b4e1fd865356c89a61abf1f   
9     0254bd905dc677a6078990aad3331a36  5bf226cf882c5bf4247f89a97c86f273   
...                                ...                               ...   
1836  f6a856dbc72d2a8bb09d860da9215545  3ac745c240dae78ad2e1b9e191e92143   
1863  fbb7c6f69326ad5bf986c099bedefdb4  4608a27e9e60c05b054631def491e7af   
1864  fbb7c6f69326ad5bf986c099bedefdb4  d351ad232c9e018edafa9f34f5d03e63   
1876  fe5c833752953fed3209646f1f63b53c  d3775e436e60258e62e678a0f68a0f8d   
1877  fe5c833752953fed3209646f1f63b53c  4863e15fa53273cc7219c58f5ffda4fb   

      review_score review_comment_title  \
0                1                  NaN   
1                1                  NaN   
5                1                  NaN   
6                1                  NaN   
9                1                  NaN   
...            ...                  ...   
1836             4                  NaN   
1863             1        não recomendo   
1864             1        não recomendo   
1876             1                  NaN   
1877             1                  NaN   

                                 review_comment_message review_creation_date  \
0     O cartucho "original HP" 60XL não é reconhecid...  2018-03-07 00:00:00   
1     O cartucho "original HP" 60XL não é reconhecid...  2018-03-07 00:00:00   
5     Produto entregue dentro de embalagem do fornec...  2018-03-07 00:00:00   
6     Produto entregue dentro de embalagem do fornec...  2018-03-07 00:00:00   
9     O pedido consta de 2 produtos e até agora rece...  2017-09-09 00:00:00   
...                                                 ...                  ...   
1836  Pagamos frete para receber o produto em casa ....  2018-02-01 00:00:00   
1863              produto não veio conforme o comprado.  2018-08-08 00:00:00   
1864              produto não veio conforme o comprado.  2018-08-08 00:00:00   
1876  Comprei dois produtos e ambos, mesmo enviados ...  2018-02-28 00:00:00   
1877  Comprei dois produtos e ambos, mesmo enviados ...  2018-02-28 00:00:00   

     review_answer_timestamp  order_item_id                        product_id  \
0        2018-03-20 18:08:23            1.0  36f60d45225e60c7da4558b070ce4b60   
1        2018-03-20 18:08:23            1.0  3f14d740544f37ece8a9e7bc8349797e   
5        2018-03-08 03:00:53            1.0  aed5efaf7a7554165f61fd016846916f   
6        2018-03-08 03:00:53            1.0  ab1f9387c0627dd24000bfbc54fdeee0   
9        2017-09-13 09:52:44            1.0  32bb152336c896d906a6344cdbe1993c   
...                      ...            ...                               ...   
1836     2018-02-01 17:25:34            1.0  e5eadf9be70a4a9fa514019542fc330a   
1863     2018-08-10 13:14:46            NaN                               NaN   
1864     2018-08-10 13:14:46            1.0  b98d41e46b20c7a6f0e509d1c76d8823   
1876     2018-02-28 13:57:52            1.0  6f5a84d79bc9f79ecd9095e91fc47a2d   
1877     2018-02-28 13:57:52            1.0  ee0c1cf2fbeae95205b4aa506f1469f0   

                             seller_id  ...   price  freight_value  \
0     00fc707aaaad2d31347cf883cd2dfe10  ...   89.15          25.90   
1     6973a06f484aacf400ece213dbf3d946  ...   84.89          15.34   
5     6a8b085f816a1f75f92dbac6eb545f8f  ...   61.50          11.93   
6     8b321bb669392f5163d04c59e235e066  ...   12.25           7.78   
9     1025f0e2d44d7041d6cf58b6550e0bfa  ...  230.00          16.36   
...                                ...  ...     ...            ...   
1836  4559697a8f7e637227c2eeaed843baff  ...   69.90          17.74   
1863                               NaN  ...     NaN            NaN   
1864  06e5eefc71ec47ae763c5c6f8db70

In [68]:
# Investigate the review message found in the last 2 rows
duplicate_review_id_products_df['review_comment_message'].iloc[-1]

'Comprei dois produtos e ambos, mesmo enviados em dias diferentes, estão como em "dificuldade na entrega" segundo o rastreamento dos Correios. O que nunca me aconteceu antes.'

Translation: I bought two products and both, even though they were sent on different days, are experiencing "difficulty in delivery" according to the Post Office's tracking. Which has never happened to me before.'

From the table above, we can observe that the entries with the same review_id but different order_id are actually different products that are receiving the same review by the customer. This can be shown as the last 2 rows shows 2 different products of different categories esporte_lazer and perfumaria respectively. However, they still receive the same review, suggesting that Olist's review system allows customers to make the same review for multiple products even if they are not related. From the review observed above, in index 1877, these reviews are usually due to the products being delivered off schedule. Hence, these reviews are valid and can be applied to multiple products and orders. Hence, these duplicate reviews cannot be dropped as they can still provide qualitative information of the order.

In [69]:
# Identify the entries with duplicate order_id, including the first of each unique order_id
duplicate_order_id_df = reviews_df[reviews_df['order_id'].duplicated(keep=False)].sort_values(by='order_id')
duplicate_order_id_df

review_id                          order_id  \
25612  89a02c45c340aeeb1354a24e7d4b2c1e  0035246a40f520710769010f752e7507   
22423  2a74b0559eb58fc1ff842ecc999594cb  0035246a40f520710769010f752e7507   
22779  ab30810c29da5da8045216f0f62652a2  013056cfe49763c6f66bda03396c5ee3   
68633  73413b847f63e02bc752b364f6d05ee9  013056cfe49763c6f66bda03396c5ee3   
854    830636803620cdf8b6ffaf1b2f6e92b2  0176a6846bcb3b0d3aa3116a9a768597   
...                                 ...                               ...   
27465  5e78482ee783451be6026e5cf0c72de1  ff763b73e473d03c321bcd5a053316e8   
41355  39de8ad3a1a494fc68cc2d5382f052f4  ff850ba359507b996e8b2fbb26df8d03   
18783  80f25f32c00540d49d57796fb6658535  ff850ba359507b996e8b2fbb26df8d03   
92230  870d856a4873d3a67252b0c51d79b950  ffaabba06c9d293a3c614e0515ddbabc   
53962  5476dd0eaee7c4e2725cafb011aa758c  ffaabba06c9d293a3c614e0515ddbabc   

       review_score review_comment_title  \
25612             5                  NaN   
22423             5                  NaN   
22779             5                  NaN   
68633             4                  NaN   
854               5                  NaN   
...             ...                  ...   
27465             3                  NaN   
41355             5                  NaN   
18783             5                  NaN   
92230             3                  NaN   
53962             3                  NaN   

                                  review_comment_message review_creation_date  \
25612                                                NaN  2017-08-29 00:00:00   
22423  Estou acostumada a comprar produtos pelo barat...  2017-08-25 00:00:00   
22779                                                NaN  2018-02-22 00:00:00   
68633                                                NaN  2018-03-04 00:00:00   
854                                                  NaN  2017-12-30 00:00:00   
...                                                  ...                  ...   
27465  Não sei que haverá acontecido os demais chegaram   2017-11-18 00:00:00   
41355                       Envio rapido... Produto 100%  2017-08-16 00:00:00   
18783  Envio rapido, produto conforme descrito no anu...  2017-08-22 00:00:00   
92230                                                NaN  2017-12-20 00:00:00   
53962                                                NaN  2017-12-20 00:00:00   

      review_answer_timestamp  
25612     2017-08-30 01:59:12  
22423     2017-08-29 21:45:57  
22779     2018-02-23 12:12:30  
68633     2018-03-05 17:02:00  
854       2018-01-02 10:54:06  
...                       ...  
27465     2017-11-18 09:02:48  
41355     2017-08-17 11:56:55  
18783     2017-08-25 11:40:22  
92230     2017-12-20 18:50:16  
53962     2017-12-21 13:24:55  

[1098 rows x 7 columns]

These duplicate entries are valid. Olist's review system likely allows the customers to make more than 1 review for a single order, providing the user with the opportunity to make another review. However, this separates the qualitative data of the orders in separate rows, causing more rows to be created after merging which may impact the EDA. These reviews may need to be aggregated by combining the review messages and aggregating the review scores.

Reviews Dataset:
- 0.82% of the dataset have entries with duplicate review ids. These entries are valid and should not be dropped as these reviews are giving generalized qualititative reviews for multiple orders.
- 0.56% of the dataset have entries with duplicate order ids. These entries are valid but need to be aggregated for qualitative analysis in the EDA.

In [70]:
# Identify the duplicate entries in the orders dataset
duplicate_entries_search(orders_df)
duplicate_values_search(orders_df, 'order_id')

Total duplicate rows: 0
% of duplicate rows: 0.00%

order_id:
Total duplicate entries: 0
% of duplicate entries: 0.00%


Orders Dataset:
- No duplicate data entries.

In [71]:
# Identify the duplicate entries in the products dataset
duplicate_entries_search(products_df)
duplicate_values_search(products_df, 'product_id')

Total duplicate rows: 0
% of duplicate rows: 0.00%

product_id:
Total duplicate entries: 0
% of duplicate entries: 0.00%


In [72]:
# Identify the duplicate entries in the sellers dataset
duplicate_entries_search(sellers_df)
duplicate_values_search(sellers_df, 'seller_id')

Total duplicate rows: 0
% of duplicate rows: 0.00%

seller_id:
Total duplicate entries: 0
% of duplicate entries: 0.00%


Sellers Dataset:
- No duplicate data entries.

In [73]:
# Identify the duplicate entries in the translations dataset
duplicate_entries_search(translations_df)
duplicate_values_search(translations_df, 'product_category_name')
duplicate_values_search(translations_df, 'product_category_name_english')

Total duplicate rows: 0
% of duplicate rows: 0.00%

product_category_name:
Total duplicate entries: 0
% of duplicate entries: 0.00%

product_category_name_english:
Total duplicate entries: 0
% of duplicate entries: 0.00%


Translations Dataset:
- No duplicate data entries.

### Duplicate Check Summary
- Drop duplicate entries in the geolocation dataset
- Aggregate reviews in the reviews dataset

## Customer Check
Check the encoding and spelling of the customers' cities.

In [ ]:
# Check if the given text contains any diacritic characters.
def identify_diacritics(text):
    for char in text:
        # Normalize the character to NFD and check for combining marks
        if any(unicodedata.category(mark) == 'Mn' for mark in unicodedata.normalize('NFD', char)):
            return True
    return False

# Identify characters in the text that are not letters or diacritics.
def identify_non_letter_and_non_diacritic(text):
    # Initialise the non diacritic characters list
    non_letter_diacritic_chars = []
    
    for char in text:
        # Get the Unicode category of the character
        char_category = unicodedata.category(char)
        # 'L' = Letter categories, 'M' = Mark categories (diacritics)
        if not char_category.startswith(('L', 'M')) and char not in [' ', '-', '\'', '(', ')']:
            non_letter_diacritic_chars.append(char)
    return bool(non_letter_diacritic_chars)

In [189]:
# Identify any diacritics in the customers' cities
customers_df[customers_df['customer_city'].apply(identify_diacritics)]

Empty DataFrame
Columns: [customer_id, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state]
Index: []

In [191]:
# Identify text that may have encoding errors
customers_df[customers_df['customer_city'].apply(identify_non_letter_and_non_diacritic)]

customer_id                customer_unique_id  \
6333  94ea98eea015faad90cd64998848d18d  0b7fea4fad79c46f6c10b848e20e9115   

     customer_zip_code_prefix           customer_city customer_state  
6333                    29735  quilometro 14 do mutum             ES

Notes:
- There are no diacritics used in the customers' cities.
- There are no encoding errors in the customers' cities. The city 'quilometro 14 do mutum' is an actual city in Brazil. It was flagged to be erroneous as the function flags cities with numbers in it. However, this city actually does have a number in it and is hence not erroneous.
- No rows need to be dropped

## Geolocation Check
Identifies erroneous geolocation entries as well as check the encoding and spelling of the cities.

### Erroneous Lat and Lng
Observe the entries  in the geolocations dataset which are not in Brazil.

- The range of Brazils latitude is between -33.742. and 5.272. 
- The range of Brazils longitude is between and -73.992 and -34.792.

Source: [(Shaalaa, 2025)](https://www.shaalaa.com/question-bank-solutions/describe-the-latitudinal-and-longitudinal-extent-of-india-and-brazil_75800)

In [74]:
# Identify the locations with latitude and longitudes outside of Brazil
erroneous_lat_lng = geolocation_df[(geolocation_df['geolocation_lat'] < -33.742) | 
                                   (geolocation_df['geolocation_lat'] > 5.272) | 
                                   (geolocation_df['geolocation_lng'] < -73.992) | 
                                   (geolocation_df['geolocation_lng'] > -34.792)
]
# Observe the dataset containing the latitude and longitude entries outside of Brazil
erroneous_lat_lng

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
387565                       18243        28.008978       -15.536867   
513631                       28165        41.614052        -8.411675   
513643                       28155       -34.586422       -58.732101   
513754                       28155        42.439286        13.820214   
514429                       28333        38.381672        -6.328200   
516682                       28595        43.684961        -7.411080   
538512                       29654        29.409252       -98.484121   
538557                       29654        21.657547      -101.466766   
585242                       35179        25.995203       -98.078544   
585260                       35179        25.995245       -98.078533   
695375                       45936       -34.622400       -58.901888   
695377                       45936        38.323939        -6.775035   
697048                       46560        38.991963        -4.947823   
698466                       47310        38.268205        -7.803886   
715892                       53990        -3.845491       -32.413367   
715893                       53990        -3.853092       -32.423525   
715896                       53990        -3.846930       -32.415821   
715900                       53990        -3.848319       -32.412384   
715908                       53990        -3.853092       -32.423525   
715911                       53990        -3.848319       -32.412384   
715912                       53990        -3.844080       -32.405985   
715913                       53990        -3.846930       -32.415821   
715914                       53990        -3.852505       -32.402779   
715915                       53990        -3.844080       -32.405985   
715916                       53990        -3.853092       -32.423525   
727755                       57319        45.065933         9.341528   
732362                       58441        41.385328        -8.717342   
769333                       68275        41.146203        -8.577855   
769351                       68275        42.166805        -6.898531   
769391                       68275        42.167251        -6.898559   
769436                       68275        42.167251        -6.898559   
769489                       68275        42.167251        -6.898559   
769924                       68379        38.713128        -9.135741   
770534                       68447        42.428884        -6.873344   
822529                       78131        38.816816        -9.394625   
860562                       83252        42.184003        -8.723762   
860832                       83252        42.184003        -8.723762   
865611                       83810        39.057629        -9.400037   
965687                       95130        14.585073       121.105394   
992584                       98780       -36.605374       -64.283946   
993075                       98780       -36.603837       -64.287433   
993302                       98780       -36.603837       -64.287433   

               geolocation_city geolocation_state  
387565  bom retiro da esperanca                SP  
513631      vila nova de campos                RJ  
513643              santa maria                RJ  
513754              santa maria                RJ  
514429                   raposo                RJ  
516682                  portela                RJ  
538512   santo antônio do canaã                ES  
538557   santo antonio do canaa                ES  
585242       santana do paraíso                MG  
585260       santana do paraiso                MG  
695375                  itabata                BA  
695377                 itabatan                BA  
697048                 ibiajara                BA  
698466       santana do sobrado                BA  
715892      fernando de noronha                PE  
715893      fernando de noronha                PE  
715896      fernando de no

In [75]:
# Display the first 3 erroneous lat and lng 
erroneous_lat_lng.head(3)

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
387565                       18243        28.008978       -15.536867   
513631                       28165        41.614052        -8.411675   
513643                       28155       -34.586422       -58.732101   

               geolocation_city geolocation_state  
387565  bom retiro da esperanca                SP  
513631      vila nova de campos                RJ  
513643              santa maria                RJ

In [76]:
# Display the number of rows with erroneous latitudes and longitudes
print("Number of erroneous lat/lng entries:", erroneous_lat_lng.shape[0])

Number of erroneous lat/lng entries: 42


Cross-referencing with Google Maps:
- 28.008978, 15.536867 is located in Vega de San Mateo, Spain and not in bom retiro da esperanca, Sao Paulo
- 41.614052, -8.411675 is located in Lago, Portugal and not in vila nova de campos, Rio de Janeiro
- -34.586422, -58.732101 is located in San Miguel, Argentina and not in santa maria, Rio de Janeiro

It is assumed that the other geolocations in the table above have similarly erroneous latitude and longitude values for the zip code, city and state in Brazil. These entries need to be dropped as they do not accurately represent the zip codes or the city and state of Brazil and should not be aggregated in the .

Notes:
- There are 42 entries which are outside of Brazil's longitude and lattitude. They are data entry errors that need to be dropped.

### Encoding and Spelling
Identifies the entries that use diacritics or have encoding errors.

In [78]:
# Identify entries with cities containing diacritics
diacritics_cities_df = geolocation_df[geolocation_df['geolocation_city'].apply(identify_diacritics)]
diacritics_cities_df

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
5                             01012       -23.547762       -46.635361   
14                            01037       -23.545187       -46.637855   
17                            01024       -23.541390       -46.629899   
21                            01020       -23.552235       -46.628441   
22                            01011       -23.546690       -46.635447   
...                             ...              ...              ...   
1000094                       99940       -28.060955       -51.858637   
1000096                       99900       -27.884844       -52.230025   
1000098                       99900       -27.900022       -52.237668   
1000143                       99930       -27.913659       -52.248615   
1000147                       99900       -27.880973       -52.223206   

        geolocation_city geolocation_state  
5              são paulo                SP  
14             são paulo                SP  
17             são paulo                SP  
21             são paulo                SP  
22             são paulo                SP  
...                  ...               ...  
1000094           ibiaçá                RS  
1000096   getúlio vargas                RS  
1000098   getúlio vargas                RS  
1000143          estação                RS  
1000147   getúlio vargas                RS  

[73437 rows x 5 columns]

In [79]:
# Identify the proportion of cities with diacritics
proportion_diacritics_cities = diacritics_cities_df.shape[0] / geolocation_df.shape[0] * 100
print(f"Proportion of cities that uses diacritics: {proportion_diacritics_cities:.2f}%")

Proportion of cities that uses diacritics: 7.34%


In [80]:
# Identify text containing encoding errors
geolocation_df[geolocation_df['geolocation_city']=='maceia³']

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
726758                       57010        -9.674896       -35.756557   

       geolocation_city geolocation_state  
726758          maceia³                AL

In [90]:
# Identify text that may have encoding errors
geolocation_df[geolocation_df['geolocation_city'].apply(identify_non_letter_and_non_diacritic)]

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
106037                       04728       -23.639872       -46.713571   
308945                       13454       -22.734480       -47.380589   
377210                       17970       -21.269165       -51.668758   
421038                       21032       -22.857779       -43.252626   
491149                       25970       -22.392335       -42.989392   
525385                       28930       -22.969370       -42.029834   
538905                       29735       -19.396948       -40.905040   
539470                       29735       -19.400231       -40.905542   
698306                       47220        -9.517593       -43.014366   
726758                       57010        -9.674896       -35.756557   
786179                       71880       -15.902908       -48.049046   
823386                       78278       -15.316965       -58.006672   
851430                       81470       -25.571748       -49.334374   
896733                       87365       -24.271860       -53.069433   
896977                       87365       -24.281905       -53.074516   
897217                       87365       -24.277697       -53.074930   
900755                       88058       -27.450674       -48.401693   
977775                       96130       -31.699198       -52.155811   
977787                       96130       -31.697290       -52.156407   
977813                       96130       -31.698061       -52.156083   

                              geolocation_city geolocation_state  
106037                              sa£o paulo                SP  
308945                   santa bárbara d`oeste                SP  
377210         são joão do pau d%26apos%3balho                SP  
421038  rio de janeiro, rio de janeiro, brasil                RJ  
491149                            ´teresopolis                RJ  
525385                      ...arraial do cabo                RJ  
538905                  quilometro 14 do mutum                ES  
539470                  quilometro 14 do mutum                ES  
698306  campo alegre de lourdes, bahia, brasil                BA  
726758                                 maceia³                AL  
786179                          riacho fundo 2                DF  
823386                lambari d%26apos%3boeste                MT  
851430                                * cidade                PR  
896733                          4o. centenario                PR  
896977                           4º centenario                PR  
897217                           4º centenario                PR  
900755                    florian&oacute;polis                SC  
977775                             colônia z-3                RS  
977787                             colônia z-3                RS  
977813                             colonia z-3                RS

Notes:
- A relatively small proportion of the cities in the geolocations dataset is small (7.34%).
- They should be normalized to spellings without diacritics to normalize it with the other majority of the cities in the dataset.
- There are cities which have encoding errors in the geolocation_city field. These need to be converted to the standard name of the cities in data cleaning.

## Items Check
Investigates the outlier order with a high order_item_id.

In [ ]:
# Observes the orders with high order_item_id
items_df.sort_values(by='order_item_id', ascending=False)

order_id  order_item_id  \
57317   8272b63d03f5f79c56e9e4120aec44ef             21   
75122   ab14fdcfbe524636d65ee38360e22ce8             20   
57316   8272b63d03f5f79c56e9e4120aec44ef             20   
11951   1b15974a0141d54e36626dca3fdc731a             20   
11950   1b15974a0141d54e36626dca3fdc731a             19   
...                                  ...            ...   
112613  ffebd80e3291e811c308365936897efd              1   
112614  ffec1a6d35149778ec575d5048d44db8              1   
112615  ffecd5a79a0084f6a592288c67e3c298              1   
7882    11dd4e8d5273dee8fbe9260bd8e0e5fe              1   
112649  fffe41c64501cc87c801fd61db3f6244              1   

                              product_id                         seller_id  \
57317   79ce45dbc2ea29b22b5a261bbb7b7ee7  2709af9587499e95e803a6498a5a56e9   
75122   9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
57316   270516a3f41dc035aa87d220228f844c  2709af9587499e95e803a6498a5a56e9   
11951   ee3d532c8a438679776d222e997606b3  8e6d7754bc7e0f22c96d255ebda59eba   
11950   ee3d532c8a438679776d222e997606b3  8e6d7754bc7e0f22c96d255ebda59eba   
...                                  ...                               ...   
112613  4cc4d02efc8f249c13355147fb44e34d  d1c7fa84e48cfa21a0e595167c1c500e   
112614  437c05a395e9e47f9762e677a7068ce7  f84fa566034f5e8e880a07ec624c56af   
112615  50fd2b788dc166edd20512370dac54df  8b321bb669392f5163d04c59e235e066   
7882    f9a1a72d4069bf9570e29b9c620bef07  1f1bb1f0859883505541bdd6606193e5   
112649  350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1   

        shipping_limit_date    price  freight_value  
57317   2017-07-21 18:25:23     7.80           6.57  
75122   2017-08-30 14:30:23    98.70          14.44  
57316   2017-07-21 18:25:23     1.20           7.89  
11951   2018-03-01 02:50:48   100.00          10.12  
11950   2018-03-01 02:50:48   100.00          10.12  
...                     ...      ...            ...  
112613  2018-07-18 20:23:55   129.90          51.20  
112614  2018-03-28 02:49:46    47.65           7.39  
112615  2018-03-05 20:15:27    21.90          15.79  
7882    2017-06-16 04:23:27  1159.00          25.55  
112649  2018-06-12 17:10:13    43.00          12.79  

[112650 rows x 7 columns]

In [194]:
# Observe a sample of an order with a high order_item_id
items_df[items_df['order_id'] == '8272b63d03f5f79c56e9e4120aec44ef']

order_id  order_item_id  \
57297  8272b63d03f5f79c56e9e4120aec44ef              1   
57298  8272b63d03f5f79c56e9e4120aec44ef              2   
57299  8272b63d03f5f79c56e9e4120aec44ef              3   
57300  8272b63d03f5f79c56e9e4120aec44ef              4   
57301  8272b63d03f5f79c56e9e4120aec44ef              5   
57302  8272b63d03f5f79c56e9e4120aec44ef              6   
57303  8272b63d03f5f79c56e9e4120aec44ef              7   
57304  8272b63d03f5f79c56e9e4120aec44ef              8   
57305  8272b63d03f5f79c56e9e4120aec44ef              9   
57306  8272b63d03f5f79c56e9e4120aec44ef             10   
57307  8272b63d03f5f79c56e9e4120aec44ef             11   
57308  8272b63d03f5f79c56e9e4120aec44ef             12   
57309  8272b63d03f5f79c56e9e4120aec44ef             13   
57310  8272b63d03f5f79c56e9e4120aec44ef             14   
57311  8272b63d03f5f79c56e9e4120aec44ef             15   
57312  8272b63d03f5f79c56e9e4120aec44ef             16   
57313  8272b63d03f5f79c56e9e4120aec44ef             17   
57314  8272b63d03f5f79c56e9e4120aec44ef             18   
57315  8272b63d03f5f79c56e9e4120aec44ef             19   
57316  8272b63d03f5f79c56e9e4120aec44ef             20   
57317  8272b63d03f5f79c56e9e4120aec44ef             21   

                             product_id                         seller_id  \
57297  270516a3f41dc035aa87d220228f844c  2709af9587499e95e803a6498a5a56e9   
57298  05b515fdc76e888aada3c6d66c201dff  2709af9587499e95e803a6498a5a56e9   
57299  05b515fdc76e888aada3c6d66c201dff  2709af9587499e95e803a6498a5a56e9   
57300  05b515fdc76e888aada3c6d66c201dff  2709af9587499e95e803a6498a5a56e9   
57301  05b515fdc76e888aada3c6d66c201dff  2709af9587499e95e803a6498a5a56e9   
57302  05b515fdc76e888aada3c6d66c201dff  2709af9587499e95e803a6498a5a56e9   
57303  05b515fdc76e888aada3c6d66c201dff  2709af9587499e95e803a6498a5a56e9   
57304  05b515fdc76e888aada3c6d66c201dff  2709af9587499e95e803a6498a5a56e9   
57305  05b515fdc76e888aada3c6d66c201dff  2709af9587499e95e803a6498a5a56e9   
57306  05b515fdc76e888aada3c6d66c201dff  2709af9587499e95e803a6498a5a56e9   
57307  05b515fdc76e888aada3c6d66c201dff  2709af9587499e95e803a6498a5a56e9   
57308  270516a3f41dc035aa87d220228f844c  2709af9587499e95e803a6498a5a56e9   
57309  270516a3f41dc035aa87d220228f844c  2709af9587499e95e803a6498a5a56e9   
57310  270516a3f41dc035aa87d220228f844c  2709af9587499e95e803a6498a5a56e9   
57311  270516a3f41dc035aa87d220228f844c  2709af9587499e95e803a6498a5a56e9   
57312  270516a3f41dc035aa87d220228f844c  2709af9587499e95e803a6498a5a56e9   
57313  270516a3f41dc035aa87d220228f844c  2709af9587499e95e803a6498a5a56e9   
57314  270516a3f41dc035aa87d220228f844c  2709af9587499e95e803a6498a5a56e9   
57315  270516a3f41dc035aa87d220228f844c  2709af9587499e95e803a6498a5a56e9   
57316  270516a3f41dc035aa87d220228f844c  2709af9587499e95e803a6498a5a56e9   
57317  79ce45dbc2ea29b22b5a261bbb7b7ee7  2709af9587499e95e803a6498a5a56e9   

       shipping_limit_date  price  freight_value  
57297  2017-07-21 18:25:23    1.2           7.89  
57298  2017-07-21 18:25:23    1.2           7.89  
57299  2017-07-21 18:25:23    1.2           7.89  
57300  2017-07-21 18:25:23    1.2           7.89  
57301  2017-07-21 18:25:23    1.2           7.89  
57302  2017-07-21 18:25:23    1.2           7.89  
57303  2017-07-21 18:25:23    1.2           7.89  
57304  2017-07-21 18:25:23    1.2           7.89  
57305  2017-07-21 18:25:23    1.2           7.89  
57306  2017-07-21 18:25:23    1.2           7.89  
57307  2017-07-21 18:25:23    1.2           7.89  
57308  2017-07-21 18:25:23    1.2           7.89  
57309  2017-07-21 18:25:23    1.2           7.89  
57310  2017-07-21 18:25:23    1.2           7.89  
57311  2017-07-21 18:25:23    1.2           7.89  
57312  2017-07-21 18:25:23    1.2           7.89  
57313  2017-07-21 18:25:23    1.2           7.89  
57314  2017-07-21 18:25:23    1.2           7.89  
57315  2017-07-21 18:25:23    1.2           7.89  
57316  2017-07-21 18:25:23    1.2      

In [195]:
# Observe another sample of an order with a high order_item_id
items_df[items_df['order_id'] == 'ab14fdcfbe524636d65ee38360e22ce8']

order_id  order_item_id  \
75103  ab14fdcfbe524636d65ee38360e22ce8              1   
75104  ab14fdcfbe524636d65ee38360e22ce8              2   
75105  ab14fdcfbe524636d65ee38360e22ce8              3   
75106  ab14fdcfbe524636d65ee38360e22ce8              4   
75107  ab14fdcfbe524636d65ee38360e22ce8              5   
75108  ab14fdcfbe524636d65ee38360e22ce8              6   
75109  ab14fdcfbe524636d65ee38360e22ce8              7   
75110  ab14fdcfbe524636d65ee38360e22ce8              8   
75111  ab14fdcfbe524636d65ee38360e22ce8              9   
75112  ab14fdcfbe524636d65ee38360e22ce8             10   
75113  ab14fdcfbe524636d65ee38360e22ce8             11   
75114  ab14fdcfbe524636d65ee38360e22ce8             12   
75115  ab14fdcfbe524636d65ee38360e22ce8             13   
75116  ab14fdcfbe524636d65ee38360e22ce8             14   
75117  ab14fdcfbe524636d65ee38360e22ce8             15   
75118  ab14fdcfbe524636d65ee38360e22ce8             16   
75119  ab14fdcfbe524636d65ee38360e22ce8             17   
75120  ab14fdcfbe524636d65ee38360e22ce8             18   
75121  ab14fdcfbe524636d65ee38360e22ce8             19   
75122  ab14fdcfbe524636d65ee38360e22ce8             20   

                             product_id                         seller_id  \
75103  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75104  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75105  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75106  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75107  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75108  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75109  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75110  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75111  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75112  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75113  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75114  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75115  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75116  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75117  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75118  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75119  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75120  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75121  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   
75122  9571759451b1d780ee7c15012ea109d4  ce27a3cc3c8cc1ea79d11e561e9bebb6   

       shipping_limit_date  price  freight_value  
75103  2017-08-30 14:30:23   98.7          14.44  
75104  2017-08-30 14:30:23   98.7          14.44  
75105  2017-08-30 14:30:23   98.7          14.44  
75106  2017-08-30 14:30:23   98.7          14.44  
75107  2017-08-30 14:30:23   98.7          14.44  
75108  2017-08-30 14:30:23   98.7          14.44  
75109  2017-08-30 14:30:23   98.7          14.44  
75110  2017-08-30 14:30:23   98.7          14.44  
75111  2017-08-30 14:30:23   98.7          14.44  
75112  2017-08-30 14:30:23   98.7          14.44  
75113  2017-08-30 14:30:23   98.7          14.44  
75114  2017-08-30 14:30:23   98.7          14.44  
75115  2017-08-30 14:30:23   98.7          14.44  
75116  2017-08-30 14:30:23   98.7          14.44  
75117  2017-08-30 14:30:23   98.7          14.44  
75118  2017-08-30 14:30:23   98.7          14.44  
75119  2017-08-30 14:30:23   98.7          14.44  
75120  2017-08-30 14:30:23   98.7          14.44  
75121  2017-08-30 14:30:23   98.7          14.44  
75122  2017-08-30 14:30:23   98.7          14.44

Notes:
- Orders with high order_item_id are usually orders where the same product is ordered multiple times.
- These orders with repeated purchasing of the same product may provide valuable insight into the types of products that need to be ordered in bulk/large quantities, suggesting a product that needs to be constantly purchased.
- No cleaning is needed

## Payment Check
Investigates the outliers in the payment dataset including:
- **High Payment Sequential**
- **High Payment Installments**
- **Free Orders**

### Payment Sequential
Investigate the outlier in the payment_sequential data field in the payments dataset.

In [74]:
# Identify the outlier order with 29 in the payment_sequential field
payments_df[payments_df['payment_sequential'] == 29]

order_id  payment_sequential payment_type  \
39108  fa65dad1b0e818e3ccc5cb0e39231352                  29      voucher   

       payment_installments  payment_value  
39108                     1          19.26

In [75]:
# Identify the rows of the order 'fa65dad1b0e818e3ccc5cb0e39231352'
payment_sequential_outlier = payments_df[payments_df['order_id'] == 'fa65dad1b0e818e3ccc5cb0e39231352']

# Display the number of rows and the table
print("Number of rows:", payment_sequential_outlier.shape[0])
payment_sequential_outlier

Number of rows: 29


order_id  payment_sequential payment_type  \
4885    fa65dad1b0e818e3ccc5cb0e39231352                  27      voucher   
9985    fa65dad1b0e818e3ccc5cb0e39231352                   4      voucher   
14321   fa65dad1b0e818e3ccc5cb0e39231352                   1      voucher   
17274   fa65dad1b0e818e3ccc5cb0e39231352                   9      voucher   
19565   fa65dad1b0e818e3ccc5cb0e39231352                  10      voucher   
23074   fa65dad1b0e818e3ccc5cb0e39231352                   2      voucher   
24879   fa65dad1b0e818e3ccc5cb0e39231352                  25      voucher   
28330   fa65dad1b0e818e3ccc5cb0e39231352                   5      voucher   
29648   fa65dad1b0e818e3ccc5cb0e39231352                   6      voucher   
32519   fa65dad1b0e818e3ccc5cb0e39231352                  11      voucher   
36822   fa65dad1b0e818e3ccc5cb0e39231352                  14      voucher   
39108   fa65dad1b0e818e3ccc5cb0e39231352                  29      voucher   
39111   fa65dad1b0e818e3ccc5cb0e39231352                  28      voucher   
63369   fa65dad1b0e818e3ccc5cb0e39231352                  15      voucher   
65641   fa65dad1b0e818e3ccc5cb0e39231352                   3      voucher   
68853   fa65dad1b0e818e3ccc5cb0e39231352                   8      voucher   
73537   fa65dad1b0e818e3ccc5cb0e39231352                  12      voucher   
74239   fa65dad1b0e818e3ccc5cb0e39231352                  21      voucher   
74721   fa65dad1b0e818e3ccc5cb0e39231352                  19      voucher   
77885   fa65dad1b0e818e3ccc5cb0e39231352                  13      voucher   
78050   fa65dad1b0e818e3ccc5cb0e39231352                  16      voucher   
79587   fa65dad1b0e818e3ccc5cb0e39231352                  26      voucher   
79670   fa65dad1b0e818e3ccc5cb0e39231352                  17      voucher   
80321   fa65dad1b0e818e3ccc5cb0e39231352                  18      voucher   
82593   fa65dad1b0e818e3ccc5cb0e39231352                   7      voucher   
85166   fa65dad1b0e818e3ccc5cb0e39231352                  23      voucher   
93337   fa65dad1b0e818e3ccc5cb0e39231352                  20      voucher   
99213   fa65dad1b0e818e3ccc5cb0e39231352                  24      voucher   
100606  fa65dad1b0e818e3ccc5cb0e39231352                  22      voucher   

        payment_installments  payment_value  
4885                       1          66.02  
9985                       1          29.16  
14321                      1           3.71  
17274                      1           1.08  
19565                      1          12.86  
23074                      1           8.51  
24879                      1           3.68  
28330                      1           0.66  
29648                      1           5.02  
32519                      1           4.03  
36822                      1           0.00  
39108                      1          19.26  
39111                      1          29.05  
63369                      1          14.04  
65641                      1           2.95  
68853                      1          26.02  
73537                      1           3.60  
74239                      1           4.11  
74721                      1           5.02  
77885                      1           0.00  
78050                      1          12.86  
79587                      1          28.27  
79670                      1           3.72  
80321                      1           0.73  
82593                      1           0.32  
85166                      1          18.86  
93337                      1         150.00  
99213                      1           0.42  
100606                     1           4.03

Briefly we can observe that there are 29 sequential payments for the order fa65dad1b0e818e3ccc5cb0e39231352. Olist likely considers different vouchers as different payment methods and in this case, the customer used 29 of them to pay for the order fully. However, we need to make sure that the sequential payments for the other orders are not missing.

In [94]:
# Identify the count of order id in the order_id data field
count_order_id = payments_df['order_id'].value_counts().sort_index()

# Identify the max value in the payment_sequential data field for each order id
max_payment_sequential_per_order = payments_df.groupby('order_id')['payment_sequential'].max().sort_index()

# Compare the count of order IDs to the maximum payment_sequential value
comparison = (count_order_id != max_payment_sequential_per_order)

# Count the number of order ids without the matching number of payment sequential
print("Number of orders without matching payment sequential:", comparison.sum())

Number of orders without matching payment sequential: 80


In [95]:
# Observe some of the orders which do not have matching payment sequential
missing_payment_sequential = comparison[comparison == True]
missing_payment_sequential

order_id
00ac05fe0fc047c54418098eb64e3aaa    True
056c68d093c100017aab1f00f260705c    True
0668d086b3ae41adde3aed3dacbc8fae    True
0a7d898c6305101e69e9f5a05cd0130d    True
0d0e88a418636d40ea780339701db49c    True
                                    ... 
f0f94b7c7548150f33f5d9e7597d396f    True
f17a58e669a7f4cf7a7f227899f8abf7    True
f5691c2b1ca263490374d13d020bd950    True
fce3db7092e1f432d0ec790414b6a5e4    True
fe49c4a1416840f8ed6bd36daac85aae    True
Length: 80, dtype: bool

In [165]:
# Show all the orders in the payments dataset
missing_payment_sequential_df = payments_df[payments_df['order_id'].isin(missing_payment_sequential.index)].sort_values(by='order_id')
missing_payment_sequential_df

order_id  payment_sequential payment_type  \
27191  00ac05fe0fc047c54418098eb64e3aaa                   2   debit_card   
12785  056c68d093c100017aab1f00f260705c                   2   debit_card   
40318  0668d086b3ae41adde3aed3dacbc8fae                   2   debit_card   
84637  0a7d898c6305101e69e9f5a05cd0130d                   2  credit_card   
82233  0d0e88a418636d40ea780339701db49c                   2   debit_card   
...                                 ...                 ...          ...   
70969  f0f94b7c7548150f33f5d9e7597d396f                   2   debit_card   
49746  f17a58e669a7f4cf7a7f227899f8abf7                   2   debit_card   
6200   f5691c2b1ca263490374d13d020bd950                   2   debit_card   
15767  fce3db7092e1f432d0ec790414b6a5e4                   2   debit_card   
59374  fe49c4a1416840f8ed6bd36daac85aae                   2   debit_card   

       payment_installments  payment_value  
27191                     1         123.47  
12785                     1          52.78  
40318                     1         252.74  
84637                     5         215.47  
82233                     1         121.09  
...                     ...            ...  
70969                     1         148.95  
49746                     1         230.15  
6200                      1         172.98  
15767                     1          66.38  
59374                     1         190.28  

[82 rows x 5 columns]

There are 80 unique orders whose entries do not match their payment sequential. This means that some payment entries are missing. For example, the order 00ac05fe0fc047c54418098eb64e3aaa is missing the payment entry containing payment_sequential 1. It only has a single payment with payment sequential 2 which is the second payment method. The first payment method is missing. This suggests that there are missing payment details of these 80 orders or they are data entry errors and the payment sequential values are erroneous

In [166]:
# Merge with items dataset to identify if the payment values adds up to the products price and freight price
missing_payment_sequential_df = missing_payment_sequential_df.merge(items_df, how='left', on='order_id')

# Combine the price and freight value the different products for each unique order
missing_payment_sequential_df = missing_payment_sequential_df.groupby('order_id').agg({
    'payment_value': lambda x: x.mode()[0] if not x.mode().empty else None,
    'price': 'sum',
    'freight_value': 'sum'
})

# Sum up the price and freight value and compare it with the payment_value
missing_payment_sequential_df['total_order_cost'] = missing_payment_sequential_df['price'] + missing_payment_sequential_df['freight_value']
missing_payment_sequential_df

payment_value   price  freight_value  \
order_id                                                                 
00ac05fe0fc047c54418098eb64e3aaa         123.47   99.90          23.57   
056c68d093c100017aab1f00f260705c          52.78   39.99          12.79   
0668d086b3ae41adde3aed3dacbc8fae         252.74  209.00          43.74   
0a7d898c6305101e69e9f5a05cd0130d         215.47  196.00          19.47   
0d0e88a418636d40ea780339701db49c         121.09   99.90          21.19   
...                                         ...     ...            ...   
f0f94b7c7548150f33f5d9e7597d396f         148.95    0.00           0.00   
f17a58e669a7f4cf7a7f227899f8abf7         230.15  213.90          16.25   
f5691c2b1ca263490374d13d020bd950         172.98  134.90          38.08   
fce3db7092e1f432d0ec790414b6a5e4          66.38   58.99           7.39   
fe49c4a1416840f8ed6bd36daac85aae         190.28  169.90          20.38   

                                  total_order_cost  
order_id                                            
00ac05fe0fc047c54418098eb64e3aaa            123.47  
056c68d093c100017aab1f00f260705c             52.78  
0668d086b3ae41adde3aed3dacbc8fae            252.74  
0a7d898c6305101e69e9f5a05cd0130d            215.47  
0d0e88a418636d40ea780339701db49c            121.09  
...                                            ...  
f0f94b7c7548150f33f5d9e7597d396f              0.00  
f17a58e669a7f4cf7a7f227899f8abf7            230.15  
f5691c2b1ca263490374d13d020bd950            172.98  
fce3db7092e1f432d0ec790414b6a5e4             66.38  
fe49c4a1416840f8ed6bd36daac85aae            190.28  

[80 rows x 4 columns]

In [169]:
# Identify the payment_value which does not match the total_order_cost
missing_payment_sequential_df[
    (missing_payment_sequential_df['payment_value'] - missing_payment_sequential_df['total_order_cost']).abs() > 0.05
]

payment_value   price  freight_value  \
order_id                                                                 
a079628ac8002126e75f86b0f87332e4          50.00  199.98         105.66   
a4431cbd79dbddaae7988ce6091cbc3c          20.00   55.80          36.60   
f0f94b7c7548150f33f5d9e7597d396f         148.95    0.00           0.00   

                                  total_order_cost  
order_id                                            
a079628ac8002126e75f86b0f87332e4            305.64  
a4431cbd79dbddaae7988ce6091cbc3c             92.40  
f0f94b7c7548150f33f5d9e7597d396f              0.00

In [175]:
# Identify why the price and freight value of f0f94b7c7548150f33f5d9e7597d396f is 0
items_df[items_df['order_id'] == 'f0f94b7c7548150f33f5d9e7597d396f']

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [172]:
# Check the payments of the order a079628ac8002126e75f86b0f87332e4
payments_df[payments_df['order_id']=='a079628ac8002126e75f86b0f87332e4']

order_id  payment_sequential payment_type  \
10258  a079628ac8002126e75f86b0f87332e4                   3  credit_card   
36471  a079628ac8002126e75f86b0f87332e4                   2   debit_card   

       payment_installments  payment_value  
10258                     3         102.82  
36471                     1          50.00

In [173]:
# Check the payments of the order a4431cbd79dbddaae7988ce6091cbc3c
payments_df[payments_df['order_id']=='a4431cbd79dbddaae7988ce6091cbc3c']

order_id  payment_sequential payment_type  \
60570  a4431cbd79dbddaae7988ce6091cbc3c                   2   debit_card   
90465  a4431cbd79dbddaae7988ce6091cbc3c                   3   debit_card   

       payment_installments  payment_value  
60570                     1           26.2  
90465                     1           20.0

We can determine that there are 2 orders 'a4431cbd79dbddaae7988ce6091cbc3c' and 'a4431cbd79dbddaae7988ce6091cbc3c' that are missing payments. The other 78 orders have payments which add up to the price of the products and freight costs, hence their payment sequential values are erroneous and there were no missing payments.

Notes:
- The orders with 21 payment sequential are valid and can be acheived using vouchers in Olist.
- There are 2 orders which are missing payments which need to be imputed.
- There are 78 orders with erroneous payment_sequential values that need to be corrected.

### Payment Installments
Investigate the outliers in payment installments.

In [179]:
# Identify outliers with high payment installments
payments_df.sort_values(by='payment_installments', ascending=False).head(20)

order_id  payment_sequential payment_type  \
10791   859f516f2fc3f95772e63c5757ab0d5b                   1  credit_card   
63893   d8d5cc8b2d42cce90b7ea35e5691a7b1                   1  credit_card   
21713   6ae2e8b8fac02522481d2a2f4ca4412c                   1  credit_card   
82431   1800f4a4362310d7eb38281634f6dfd1                   1  credit_card   
60027   ef71772d55431467890fda2f45c7bdde                   1  credit_card   
102008  f60ce04ff8060152c83c7c97e246d6a8                   1  credit_card   
55094   fcbb6af360b31b05460c2c8e524588c0                   1  credit_card   
102435  e02d61b42452cc6737650331d8bc8ad7                   1  credit_card   
18512   2b7dbe9be72b8f9733844c31055c0825                   1  credit_card   
2970    70b7e94ea46d3e8b5bc12a50186edaf0                   1  credit_card   
66746   fe808fc011ee4ae41f2ed8d1d52b6670                   1  credit_card   
50401   ffb18bf111fa70edf316eb0390427986                   1  credit_card   
90639   d74fca7ee2ce7587c45eefb0fea95ed8                   1  credit_card   
52846   63dbe0c8e63e5f1b4deec09d4f044a7f                   1  credit_card   
23024   90f864fe19d11549fa01eb81c4dd87e3                   1  credit_card   
12307   ff36cbc44b8f228e0449c92ef089c843                   1  credit_card   
36088   84d2098c97827c6327ed4d7be95e1fc8                   1  credit_card   
87593   61450e6c8f56d52e46a198e57df7d731                   1  credit_card   
89969   657092a7391a08ae27775a441765b3bc                   1  credit_card   
18956   ef00af19f3e4667ac596baf6656e0ee4                   1  credit_card   

        payment_installments  payment_value  
10791                     24         609.56  
63893                     24         599.18  
21713                     24         433.43  
82431                     24         325.37  
60027                     24         629.64  
102008                    24        1440.10  
55094                     24        1194.38  
102435                    24         515.70  
18512                     24         345.39  
2970                      24         274.84  
66746                     24         241.42  
50401                     24         617.24  
90639                     24        1099.00  
52846                     24         771.69  
23024                     24         588.58  
12307                     24         756.49  
36088                     24         286.78  
87593                     24         252.09  
89969                     23         236.48  
18956                     22         228.71

Notes:
- These are valid entries as they are high costing products which are paid using credit cards which allow long term payments.

## Product Check
Investigate the low outlier value in the product weight field in the products dataset.

In [78]:
# Identify the products with low weight in the products dataset
products_df.sort_values(by='product_weight_g').head(10)

product_id product_category_name  \
9769   81781c0fed9fe1ad6e8c81fca1e1cb08       cama_mesa_banho   
32079  e673e90efa65a5409ff4196c038bb5af       cama_mesa_banho   
14997  36ba42dd187055e1fbe943b2d11430ca       cama_mesa_banho   
13683  8038040ee2a71048d4bdbbdc985b69ab       cama_mesa_banho   
15374  f9fafac43d3416d92ecc303fdeb1743d      moveis_decoracao   
15675  8aae4df46baf1278422b69edbb50bd35      moveis_decoracao   
9396   ad7d07f5775feab3f20504d1ad3fff11      moveis_decoracao   
16181  5837bba0ce6e35e6f2dc5c3e223e3276      moveis_decoracao   
13397  7ddb76f2c7237acc852358b95e7946a8             papelaria   
9371   632921e8d6c6b23ae47ff20950a56854       cama_mesa_banho   

       product_name_lenght  product_description_lenght  product_photos_qty  \
9769                  51.0                       529.0                 1.0   
32079                 53.0                       528.0                 1.0   
14997                 53.0                       528.0                 1.0   
13683                 48.0                       528.0                 1.0   
15374                 51.0                      1039.0                 2.0   
15675                 56.0                      1002.0                 2.0   
9396                  50.0                      1002.0                 2.0   
16181                 52.0                      1041.0                 2.0   
13397                 49.0                      1048.0                 2.0   
9371                  50.0                       506.0                 1.0   

       product_weight_g  product_length_cm  product_height_cm  \
9769                0.0               30.0               25.0   
32079               0.0               30.0               25.0   
14997               0.0               30.0               25.0   
13683               0.0               30.0               25.0   
15374               2.0               11.0               11.0   
15675               2.0               11.0               11.0   
9396                2.0               11.0               11.0   
16181               2.0               11.0               11.0   
13397               2.0               11.0               11.0   
9371               25.0               45.0               18.0   

       product_width_cm  
9769               30.0  
32079              30.0  
14997              30.0  
13683              30.0  
15374              52.0  
15675              52.0  
9396               52.0  
16181              52.0  
13397              52.0  
9371               35.0

Notes:
- There are some products with abnormal masses of 0g. These are likely items which are very light and thus their measurements were rounded down to zero in the dataset. The products which have 0g may be cloths or mats used for bedrooms, dining rooms or bathrooms. Hence these values are valid.
- These values should not be dropped.

## Sellers Check
Identify any encoding errors or inconsistent diacritics usage in cities.

In [182]:
sellers_df

seller_id seller_zip_code_prefix  \
0     3442f8959a84dea7ee197c632cb2df15                  13023   
1     d1b65fc7debc3361ea86b5f14c68d2e2                  13844   
2     ce3ad9de960102d0677a81f5d0bb7b2d                  20031   
3     c0f3eea2e14555b6faeea3dd58c1b1c3                  04195   
4     51a04a8a6bdcb23deccc82b0b80742cf                  12914   
...                                ...                    ...   
3090  98dddbc4601dd4443ca174359b237166                  87111   
3091  f8201cab383e484733266d1906e2fdfa                  88137   
3092  74871d19219c7d518d0090283e03c137                  04650   
3093  e603cf3fec55f8697c9059638d6c8eb5                  96080   
3094  9e25199f6ef7e7c347120ff175652c3b                  12051   

            seller_city seller_state  
0              campinas           SP  
1            mogi guacu           SP  
2        rio de janeiro           RJ  
3             sao paulo           SP  
4     braganca paulista           SP  
...                 ...          ...  
3090            sarandi           PR  
3091            palhoca           SC  
3092          sao paulo           SP  
3093            pelotas           RS  
3094            taubate           SP  

[3095 rows x 4 columns]

In [183]:
# Identify entries with cities containing diacritics
sellers_df[sellers_df['seller_city'].apply(identify_diacritics)]


seller_id seller_zip_code_prefix seller_city  \
360  a3fa18b3f688ec0fca3eb8bfcbd2d5b3                  04557  são paulo   

    seller_state  
360           SP

In [184]:
# Identify text that may have encoding errors
sellers_df[sellers_df['seller_city'].apply(identify_non_letter_and_non_diacritic)]

seller_id seller_zip_code_prefix  \
237   c3aad7dc65449ae90a5e9c3c6c1e78e0                  15350   
246   71593c7413973a1e160057b80d4958f6                  03407   
476   26b482dccfa29bd2e40703ba45523702                  13450   
517   ceb7b4fb9401cd378de7886317ad1b47                  22790   
551   723a46b89fd5c3ed78ccdf039e33ac63                  93310   
622   7994b065a7ffb14e71c6312cf87b9de2                  29142   
869   cbf09e831b0c11f6f23ffb51004db972                  09726   
945   f52c2422904463fdd7741f99045fecb6                  09230   
1004  1cbd32d00d01bb8087a5eb088612fd9c                  03363   
1159  89dda63a3c907c468ec88c310ed91213                  09380   
1337  720e6cf846ea7572cbb66b743fb91e6c                  08717   
1346  cf1313c6e2c01c2f4b014f97db4bcd2b                  22050   
1447  fe9d9cf8631285d5982c6e2cf27fb114                  36200   
1649  d79e8478eed9999493990b44955fb22e                  20081   
1712  6025c79c035c3d772133b8b8238463b2                  83327   
1920  01fd077212124329bac32490e8ef80d9                  14079   
2162  a1bea7061f61f6fdd9a85a6325ba1033                  06311   
2258  4b5f66b7adcf57f1ecc0d3c07dd6b177                  87025   
2340  5dceca129747e92ff8ef7a997dc4f8ca                  13450   
2620  6a3139c7bf09ece22a4713d956acbe5e                  13790   
2988  f9eedec3129e8cc6b6429c42d0808c5b                  22793   
3015  7f5e4d5efad7e44b91115dd1decb65f3                  12306   

                                   seller_city seller_state  
237                               auriflama/sp           SP  
246                      sao paulo / sao paulo           SP  
476                      santa barbara d´oeste           SP  
517                                   04482255           RJ  
551   novo hamburgo, rio grande do sul, brasil           RS  
622                             cariacica / es           ES  
869                                     sbc/sp           SP  
945                      santo andre/sao paulo           SP  
1004                                   sp / sp           SP  
1159                            maua/sao paulo           SP  
1337                      mogi das cruzes / sp           SP  
1346            rio de janeiro \rio de janeiro           RJ  
1447                   barbacena/ minas gerais           MG  
1649           rio de janeiro / rio de janeiro           RJ  
1712                                pinhais/pr           PR  
1920                ribeirao preto / sao paulo           SP  
2162                   carapicuiba / sao paulo           SP  
2258                 vendas@creditparts.com.br           PR  
2340                     santa barbara d´oeste           SP  
2620                 sao sebastiao da grama/sp           SP  
2988    rio de janeiro, rio de janeiro, brasil           RJ  
3015                       jacarei / sao paulo           SP

Notes:
- There is only 1 row which uses a diacritic. Needs to be normalized as well.
- There are values in the seller_city that contain both the city and state delimited by a '/' or '\'.
- There are also values in the seller_city that are not even cities such as 'vendas@creditparts.com.br'

# Conclusion

**Customers**
- No need for cleaning.

**Items**
- No need for cleaning.

**Geolocations**
- Drop the entries with erroneous latitude and longitude in the geolocations dataset.
- Aggregate the latitude and longitude data of the geolocations dataset by zip code.
- Standardize the spellings of the cities, converting diacritics to standard alphabet.
- Correct encoding or other errors in the city names.

**Products**
- Drop rows of products with missing information of the product i.e. rows with null in all columns except product_id.
- Impute missing entries in the products dataset using iterative imputing.

**Orders**
- Drop the order_approved_at and order_delivered_carrier_date fields.
- Feature engineer a new column from the 'order_delivered_customer_date' and the 'order_estimated_delivery_date' field to represent the difference from expected delivery date.

**Reviews**
- Drop the fields 'review_comment_title' and 'review_comment_message' fields.

**Payments**
- There are 2 orders which are missing payments which need to be imputed.
- There are 78 orders with erroneous payment_sequential values that need to be corrected.

**Sellers**
- Standardize the spellings of the cities, converting diacritics to standard alphabet.
- Correct encoding or other errors in the city names.